test_that("'iv_X' and 'tv_X' works", {
  # dim(X) = c(ncol(X), length_of_sequences, n_sequences)
  x1 <- data.table(id = rep(1:2, each = 5), time = 1:5, 2, x = 1:5)
  expect_true(tv_X(x1, "x"))
  expect_false(iv_X(x1, "x"))
  x2 <- data.table(id = rep(1:2, each = 5), time = 1:5, x = 1:10)
  expect_true(tv_X(x2, "x"))
  expect_true(iv_X(x2, "x"))
  x3 <- data.table(id = rep(1:2, each = 5), time = 1:5, x = rep(1:2, each = 5))
  expect_false(tv_X(x3, "x"))
  expect_true(iv_X(x3, "x"))
  x4 <- data.table(id = rep(1:2, each = 5), time = 1:5, x = 1)
  expect_false(tv_X(x4, "x"))
  expect_false(iv_X(x4, "x"))
})
