// Generated by rstantools.  Do not edit by hand.

/*
    seqHMM is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    seqHMM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with seqHMM.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_nhmm_ccc_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 144> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 83, column 2 to column 32)",
  " (in 'string', line 85, column 2 to column 41)",
  " (in 'string', line 87, column 2 to column 41)",
  " (in 'string', line 90, column 2 to column 15)",
  " (in 'string', line 91, column 2 to column 64)",
  " (in 'string', line 92, column 2 to column 33)",
  " (in 'string', line 93, column 2 to column 33)",
  " (in 'string', line 99, column 2 to column 57)",
  " (in 'string', line 95, column 4 to column 57)",
  " (in 'string', line 96, column 4 to column 57)",
  " (in 'string', line 94, column 16 to line 97, column 3)",
  " (in 'string', line 94, column 2 to line 97, column 3)",
  " (in 'string', line 101, column 4 to column 58)",
  " (in 'string', line 102, column 4 to column 58)",
  " (in 'string', line 100, column 16 to line 103, column 3)",
  " (in 'string', line 100, column 2 to line 103, column 3)",
  " (in 'string', line 105, column 11 to column 12)",
  " (in 'string', line 105, column 4 to column 17)",
  " (in 'string', line 106, column 11 to column 12)",
  " (in 'string', line 106, column 4 to column 21)",
  " (in 'string', line 107, column 11 to column 12)",
  " (in 'string', line 107, column 14 to column 19)",
  " (in 'string', line 107, column 4 to column 27)",
  " (in 'string', line 108, column 11 to column 12)",
  " (in 'string', line 108, column 14 to column 15)",
  " (in 'string', line 108, column 4 to column 24)",
  " (in 'string', line 109, column 11 to column 12)",
  " (in 'string', line 109, column 14 to column 15)",
  " (in 'string', line 109, column 4 to column 23)",
  " (in 'string', line 110, column 4 to column 38)",
  " (in 'string', line 112, column 6 to column 48)",
  " (in 'string', line 111, column 18 to line 113, column 5)",
  " (in 'string', line 111, column 4 to line 113, column 5)",
  " (in 'string', line 115, column 4 to column 49)",
  " (in 'string', line 114, column 16 to line 116, column 3)",
  " (in 'string', line 114, column 2 to line 116, column 3)",
  " (in 'string', line 119, column 8 to column 41)",
  " (in 'string', line 118, column 20 to line 120, column 7)",
  " (in 'string', line 118, column 6 to line 120, column 7)",
  " (in 'string', line 121, column 6 to column 44)",
  " (in 'string', line 117, column 18 to line 122, column 5)",
  " (in 'string', line 117, column 4 to line 122, column 5)",
  " (in 'string', line 123, column 4 to column 22)",
  " (in 'string', line 104, column 2 to line 124, column 3)",
  " (in 'string', line 127, column 2 to column 18)",
  " (in 'string', line 128, column 2 to column 20)",
  " (in 'string', line 64, column 2 to column 17)",
  " (in 'string', line 65, column 2 to column 17)",
  " (in 'string', line 66, column 2 to column 17)",
  " (in 'string', line 67, column 2 to column 17)",
  " (in 'string', line 68, column 8 to column 9)",
  " (in 'string', line 68, column 11 to column 12)",
  " (in 'string', line 68, column 2 to column 44)",
  " (in 'string', line 69, column 2 to column 19)",
  " (in 'string', line 70, column 8 to column 9)",
  " (in 'string', line 70, column 11 to column 12)",
  " (in 'string', line 70, column 21 to column 24)",
  " (in 'string', line 70, column 2 to column 30)",
  " (in 'string', line 71, column 2 to column 19)",
  " (in 'string', line 72, column 8 to column 9)",
  " (in 'string', line 72, column 11 to column 12)",
  " (in 'string', line 72, column 21 to column 24)",
  " (in 'string', line 72, column 2 to column 30)",
  " (in 'string', line 73, column 2 to column 19)",
  " (in 'string', line 74, column 8 to column 9)",
  " (in 'string', line 74, column 18 to column 21)",
  " (in 'string', line 74, column 2 to column 27)",
  " (in 'string', line 77, column 13 to column 16)",
  " (in 'string', line 77, column 2 to column 57)",
  " (in 'string', line 78, column 13 to column 16)",
  " (in 'string', line 78, column 2 to column 57)",
  " (in 'string', line 79, column 13 to column 16)",
  " (in 'string', line 79, column 2 to column 57)",
  " (in 'string', line 83, column 9 to column 14)",
  " (in 'string', line 83, column 16 to column 19)",
  " (in 'string', line 85, column 8 to column 9)",
  " (in 'string', line 85, column 18 to column 23)",
  " (in 'string', line 85, column 25 to column 28)",
  " (in 'string', line 87, column 8 to column 9)",
  " (in 'string', line 87, column 18 to column 23)",
  " (in 'string', line 87, column 25 to column 28)",
  " (in 'string', line 91, column 9 to column 10)",
  " (in 'string', line 91, column 12 to column 15)",
  " (in 'string', line 92, column 8 to column 9)",
  " (in 'string', line 92, column 18 to column 19)",
  " (in 'string', line 92, column 21 to column 24)",
  " (in 'string', line 93, column 8 to column 9)",
  " (in 'string', line 93, column 18 to column 19)",
  " (in 'string', line 93, column 21 to column 24)",
  " (in 'string', line 6, column 4 to column 25)",
  " (in 'string', line 7, column 4 to column 25)",
  " (in 'string', line 8, column 11 to column 12)",
  " (in 'string', line 8, column 4 to column 24)",
  " (in 'string', line 9, column 11 to column 12)",
  " (in 'string', line 9, column 4 to column 28)",
  " (in 'string', line 10, column 4 to column 37)",
  " (in 'string', line 13, column 8 to column 81)",
  " (in 'string', line 12, column 21 to line 14, column 7)",
  " (in 'string', line 12, column 6 to line 14, column 7)",
  " (in 'string', line 15, column 6 to column 32)",
  " (in 'string', line 11, column 19 to line 16, column 5)",
  " (in 'string', line 11, column 4 to line 16, column 5)",
  " (in 'string', line 17, column 4 to column 34)",
  " (in 'string', line 5, column 66 to line 18, column 3)",
  " (in 'string', line 20, column 4 to column 25)",
  " (in 'string', line 21, column 4 to column 25)",
  " (in 'string', line 22, column 11 to column 12)",
  " (in 'string', line 22, column 4 to column 24)",
  " (in 'string', line 23, column 11 to column 12)",
  " (in 'string', line 23, column 4 to column 28)",
  " (in 'string', line 24, column 4 to column 37)",
  " (in 'string', line 27, column 8 to column 78)",
  " (in 'string', line 26, column 21 to line 28, column 7)",
  " (in 'string', line 26, column 6 to line 28, column 7)",
  " (in 'string', line 29, column 6 to column 32)",
  " (in 'string', line 25, column 19 to line 30, column 5)",
  " (in 'string', line 25, column 4 to line 30, column 5)",
  " (in 'string', line 31, column 4 to column 34)",
  " (in 'string', line 19, column 58 to line 32, column 3)",
  " (in 'string', line 39, column 4 to column 25)",
  " (in 'string', line 40, column 10 to column 16)",
  " (in 'string', line 40, column 4 to column 24)",
  " (in 'string', line 42, column 6 to column 25)",
  " (in 'string', line 41, column 23 to line 43, column 5)",
  " (in 'string', line 41, column 4 to line 43, column 5)",
  " (in 'string', line 44, column 4 to column 13)",
  " (in 'string', line 38, column 48 to line 45, column 3)",
  " (in 'string', line 47, column 4 to column 25)",
  " (in 'string', line 48, column 10 to column 16)",
  " (in 'string', line 48, column 4 to column 24)",
  " (in 'string', line 50, column 6 to column 22)",
  " (in 'string', line 49, column 23 to line 51, column 5)",
  " (in 'string', line 49, column 4 to line 51, column 5)",
  " (in 'string', line 52, column 4 to column 13)",
  " (in 'string', line 46, column 40 to line 53, column 3)",
  " (in 'string', line 55, column 4 to column 25)",
  " (in 'string', line 56, column 10 to column 16)",
  " (in 'string', line 56, column 4 to column 24)",
  " (in 'string', line 58, column 6 to column 22)",
  " (in 'string', line 57, column 23 to line 59, column 5)",
  " (in 'string', line 57, column 4 to line 59, column 5)",
  " (in 'string', line 60, column 4 to column 13)",
  " (in 'string', line 54, column 40 to line 61, column 3)"};
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, T1__, stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__,
       const std::vector<Eigen::Matrix<T1__,-1,-1>>& log_A, const T2__&
       log_py_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
  stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__, const T1__& log_A_arg__, const T2__&
       log_py_arg__, std::ostream* pstream__);
std::vector<int>
add(const std::vector<int>& x, const std::vector<int>& y, std::ostream*
    pstream__);
std::vector<int>
add(const int& x, const std::vector<int>& y, std::ostream* pstream__);
std::vector<int>
add(const std::vector<int>& x, const int& y, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, T1__, stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__,
       const std::vector<Eigen::Matrix<T1__,-1,-1>>& log_A, const T2__&
       log_py_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& log_Pi = stan::math::to_ref(log_Pi_arg__);
  const auto& log_py = stan::math::to_ref(log_py_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int S = std::numeric_limits<int>::min();
    current_statement__ = 90;
    S = stan::math::rows(log_py);
    int T = std::numeric_limits<int>::min();
    current_statement__ = 91;
    T = stan::math::cols(log_py);
    current_statement__ = 92;
    stan::math::validate_non_negative_index("log_alpha", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 94;
    stan::math::validate_non_negative_index("log_alpha_new", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 96;
    stan::model::assign(log_alpha,
      stan::math::add(log_Pi,
        stan::model::rvalue(log_py, "log_py", stan::model::index_omni(),
          stan::model::index_uni(1))), "assigning variable log_alpha");
    current_statement__ = 102;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 99;
      for (int k = 1; k <= S; ++k) {
        current_statement__ = 97;
        stan::model::assign(log_alpha_new,
          stan::math::log_sum_exp(
            stan::math::add(
              stan::math::add(log_alpha,
                stan::model::rvalue(log_A, "log_A",
                  stan::model::index_uni(t), stan::model::index_omni(),
                  stan::model::index_uni(k))),
              stan::model::rvalue(log_py, "log_py",
                stan::model::index_uni(k), stan::model::index_uni(t)))),
          "assigning variable log_alpha_new", stan::model::index_uni(k));
      }
      current_statement__ = 100;
      stan::model::assign(log_alpha, log_alpha_new,
        "assigning variable log_alpha");
    }
    current_statement__ = 103;
    return stan::math::log_sum_exp(log_alpha);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
  stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__, const T1__& log_A_arg__, const T2__&
       log_py_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& log_Pi = stan::math::to_ref(log_Pi_arg__);
  const auto& log_A = stan::math::to_ref(log_A_arg__);
  const auto& log_py = stan::math::to_ref(log_py_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int S = std::numeric_limits<int>::min();
    current_statement__ = 105;
    S = stan::math::rows(log_py);
    int T = std::numeric_limits<int>::min();
    current_statement__ = 106;
    T = stan::math::cols(log_py);
    current_statement__ = 107;
    stan::math::validate_non_negative_index("log_alpha", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 109;
    stan::math::validate_non_negative_index("log_alpha_new", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 111;
    stan::model::assign(log_alpha,
      stan::math::add(log_Pi,
        stan::model::rvalue(log_py, "log_py", stan::model::index_omni(),
          stan::model::index_uni(1))), "assigning variable log_alpha");
    current_statement__ = 117;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 114;
      for (int k = 1; k <= S; ++k) {
        current_statement__ = 112;
        stan::model::assign(log_alpha_new,
          stan::math::log_sum_exp(
            stan::math::add(
              stan::math::add(log_alpha,
                stan::model::rvalue(log_A, "log_A",
                  stan::model::index_omni(), stan::model::index_uni(k))),
              stan::model::rvalue(log_py, "log_py",
                stan::model::index_uni(k), stan::model::index_uni(t)))),
          "assigning variable log_alpha_new", stan::model::index_uni(k));
      }
      current_statement__ = 115;
      stan::model::assign(log_alpha, log_alpha_new,
        "assigning variable log_alpha");
    }
    current_statement__ = 118;
    return stan::math::log_sum_exp(log_alpha);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
std::vector<int>
add(const std::vector<int>& x, const std::vector<int>& y, std::ostream*
    pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int x_size = std::numeric_limits<int>::min();
    current_statement__ = 120;
    x_size = stan::math::size(x);
    current_statement__ = 121;
    stan::math::validate_non_negative_index("z", "x_size", x_size);
    std::vector<int> z =
      std::vector<int>(x_size, std::numeric_limits<int>::min());
    current_statement__ = 125;
    for (int i = 1; i <= x_size; ++i) {
      current_statement__ = 123;
      stan::model::assign(z,
        (stan::model::rvalue(x, "x", stan::model::index_uni(i)) +
        stan::model::rvalue(y, "y", stan::model::index_uni(i))),
        "assigning variable z", stan::model::index_uni(i));
    }
    current_statement__ = 126;
    return z;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
std::vector<int>
add(const int& x, const std::vector<int>& y, std::ostream* pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int y_size = std::numeric_limits<int>::min();
    current_statement__ = 128;
    y_size = stan::math::size(y);
    current_statement__ = 129;
    stan::math::validate_non_negative_index("z", "y_size", y_size);
    std::vector<int> z =
      std::vector<int>(y_size, std::numeric_limits<int>::min());
    current_statement__ = 133;
    for (int i = 1; i <= y_size; ++i) {
      current_statement__ = 131;
      stan::model::assign(z, (x +
        stan::model::rvalue(y, "y", stan::model::index_uni(i))),
        "assigning variable z", stan::model::index_uni(i));
    }
    current_statement__ = 134;
    return z;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
std::vector<int>
add(const std::vector<int>& x, const int& y, std::ostream* pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int x_size = std::numeric_limits<int>::min();
    current_statement__ = 136;
    x_size = stan::math::size(x);
    current_statement__ = 137;
    stan::math::validate_non_negative_index("z", "x_size", x_size);
    std::vector<int> z =
      std::vector<int>(x_size, std::numeric_limits<int>::min());
    current_statement__ = 141;
    for (int i = 1; i <= x_size; ++i) {
      current_statement__ = 139;
      stan::model::assign(z,
        (stan::model::rvalue(x, "x", stan::model::index_uni(i)) + y),
        "assigning variable z", stan::model::index_uni(i));
    }
    current_statement__ = 142;
    return z;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_nhmm_ccc final : public model_base_crtp<model_nhmm_ccc> {
private:
  int N;
  int T;
  int M;
  int S;
  std::vector<std::vector<int>> obs;
  int K_s;
  std::vector<std::vector<Eigen::Matrix<double,-1,1>>> X_s;
  int K_o;
  std::vector<std::vector<Eigen::Matrix<double,-1,1>>> X_o;
  int K_i;
  std::vector<Eigen::Matrix<double,-1,1>> X_i;
  Eigen::Matrix<double,1,-1> zeros_row_K_i_data__;
  Eigen::Matrix<double,1,-1> zeros_row_K_s_data__;
  Eigen::Matrix<double,1,-1> zeros_row_K_o_data__;
  int beta_i_raw_1dim__;
  int beta_s_raw_2dim__;
  int beta_o_raw_2dim__;
  Eigen::Map<Eigen::Matrix<double,1,-1>> zeros_row_K_i{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,1,-1>> zeros_row_K_s{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,1,-1>> zeros_row_K_o{nullptr, 0};
public:
  ~model_nhmm_ccc() {}
  model_nhmm_ccc(stan::io::var_context& context__, unsigned int
                 random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_nhmm_ccc_namespace::model_nhmm_ccc";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 47;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 47;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 48;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 49;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "M", M, 2);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 50;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("obs", "T", T);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("obs", "N", N);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "obs", "int",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(N)});
      obs = std::vector<std::vector<int>>(T,
              std::vector<int>(N, std::numeric_limits<int>::min()));
      {
        std::vector<int> obs_flat__;
        current_statement__ = 53;
        obs_flat__ = context__.vals_i("obs");
        current_statement__ = 53;
        pos__ = 1;
        current_statement__ = 53;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 53;
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            current_statement__ = 53;
            stan::model::assign(obs, obs_flat__[(pos__ - 1)],
              "assigning variable obs", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 53;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "obs", obs, 0);
      current_statement__ = 53;
      stan::math::check_less_or_equal(function__, "obs", obs, (M + 1));
      current_statement__ = 54;
      context__.validate_dims("data initialization", "K_s", "int",
        std::vector<size_t>{});
      K_s = std::numeric_limits<int>::min();
      current_statement__ = 54;
      K_s = context__.vals_i("K_s")[(1 - 1)];
      current_statement__ = 54;
      stan::math::check_greater_or_equal(function__, "K_s", K_s, 1);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("X_s", "T", T);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("X_s", "N", N);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("X_s", "K_s", K_s);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "X_s", "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(N),
          static_cast<size_t>(K_s)});
      X_s = std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(T,
              std::vector<Eigen::Matrix<double,-1,1>>(N,
                Eigen::Matrix<double,-1,1>::Constant(K_s,
                  std::numeric_limits<double>::quiet_NaN())));
      {
        std::vector<local_scalar_t__> X_s_flat__;
        current_statement__ = 58;
        X_s_flat__ = context__.vals_r("X_s");
        current_statement__ = 58;
        pos__ = 1;
        current_statement__ = 58;
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          current_statement__ = 58;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 58;
            for (int sym3__ = 1; sym3__ <= T; ++sym3__) {
              current_statement__ = 58;
              stan::model::assign(X_s, X_s_flat__[(pos__ - 1)],
                "assigning variable X_s", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 58;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 59;
      context__.validate_dims("data initialization", "K_o", "int",
        std::vector<size_t>{});
      K_o = std::numeric_limits<int>::min();
      current_statement__ = 59;
      K_o = context__.vals_i("K_o")[(1 - 1)];
      current_statement__ = 59;
      stan::math::check_greater_or_equal(function__, "K_o", K_o, 1);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("X_o", "T", T);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("X_o", "N", N);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("X_o", "K_o", K_o);
      current_statement__ = 63;
      context__.validate_dims("data initialization", "X_o", "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(N),
          static_cast<size_t>(K_o)});
      X_o = std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(T,
              std::vector<Eigen::Matrix<double,-1,1>>(N,
                Eigen::Matrix<double,-1,1>::Constant(K_o,
                  std::numeric_limits<double>::quiet_NaN())));
      {
        std::vector<local_scalar_t__> X_o_flat__;
        current_statement__ = 63;
        X_o_flat__ = context__.vals_r("X_o");
        current_statement__ = 63;
        pos__ = 1;
        current_statement__ = 63;
        for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
          current_statement__ = 63;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 63;
            for (int sym3__ = 1; sym3__ <= T; ++sym3__) {
              current_statement__ = 63;
              stan::model::assign(X_o, X_o_flat__[(pos__ - 1)],
                "assigning variable X_o", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 63;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 64;
      context__.validate_dims("data initialization", "K_i", "int",
        std::vector<size_t>{});
      K_i = std::numeric_limits<int>::min();
      current_statement__ = 64;
      K_i = context__.vals_i("K_i")[(1 - 1)];
      current_statement__ = 64;
      stan::math::check_greater_or_equal(function__, "K_i", K_i, 1);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("X_i", "N", N);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("X_i", "K_i", K_i);
      current_statement__ = 67;
      context__.validate_dims("data initialization", "X_i", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K_i)});
      X_i = std::vector<Eigen::Matrix<double,-1,1>>(N,
              Eigen::Matrix<double,-1,1>::Constant(K_i,
                std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> X_i_flat__;
        current_statement__ = 67;
        X_i_flat__ = context__.vals_r("X_i");
        current_statement__ = 67;
        pos__ = 1;
        current_statement__ = 67;
        for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
          current_statement__ = 67;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 67;
            stan::model::assign(X_i, X_i_flat__[(pos__ - 1)],
              "assigning variable X_i", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 67;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 68;
      stan::math::validate_non_negative_index("zeros_row_K_i", "K_i", K_i);
      current_statement__ = 69;
      zeros_row_K_i_data__ = Eigen::Matrix<double,1,-1>::Constant(K_i,
                               std::numeric_limits<double>::quiet_NaN());
      new (&zeros_row_K_i)
        Eigen::Map<Eigen::Matrix<double,1,-1>>(zeros_row_K_i_data__.data(),
        K_i);
      current_statement__ = 69;
      stan::model::assign(zeros_row_K_i, stan::math::rep_row_vector(0, K_i),
        "assigning variable zeros_row_K_i");
      current_statement__ = 70;
      stan::math::validate_non_negative_index("zeros_row_K_s", "K_s", K_s);
      current_statement__ = 71;
      zeros_row_K_s_data__ = Eigen::Matrix<double,1,-1>::Constant(K_s,
                               std::numeric_limits<double>::quiet_NaN());
      new (&zeros_row_K_s)
        Eigen::Map<Eigen::Matrix<double,1,-1>>(zeros_row_K_s_data__.data(),
        K_s);
      current_statement__ = 71;
      stan::model::assign(zeros_row_K_s, stan::math::rep_row_vector(0, K_s),
        "assigning variable zeros_row_K_s");
      current_statement__ = 72;
      stan::math::validate_non_negative_index("zeros_row_K_o", "K_o", K_o);
      current_statement__ = 73;
      zeros_row_K_o_data__ = Eigen::Matrix<double,1,-1>::Constant(K_o,
                               std::numeric_limits<double>::quiet_NaN());
      new (&zeros_row_K_o)
        Eigen::Map<Eigen::Matrix<double,1,-1>>(zeros_row_K_o_data__.data(),
        K_o);
      current_statement__ = 73;
      stan::model::assign(zeros_row_K_o, stan::math::rep_row_vector(0, K_o),
        "assigning variable zeros_row_K_o");
      current_statement__ = 74;
      beta_i_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 74;
      beta_i_raw_1dim__ = (S - 1);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("beta_i_raw", "S - 1",
        beta_i_raw_1dim__);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("beta_i_raw", "K_i", K_i);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("beta_s_raw", "S", S);
      current_statement__ = 77;
      beta_s_raw_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 77;
      beta_s_raw_2dim__ = (S - 1);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("beta_s_raw", "S - 1",
        beta_s_raw_2dim__);
      current_statement__ = 78;
      stan::math::validate_non_negative_index("beta_s_raw", "K_s", K_s);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("beta_o_raw", "S", S);
      current_statement__ = 80;
      beta_o_raw_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 80;
      beta_o_raw_2dim__ = (M - 1);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("beta_o_raw", "M - 1",
        beta_o_raw_2dim__);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("beta_o_raw", "K_o", K_o);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("beta_i", "S", S);
      current_statement__ = 83;
      stan::math::validate_non_negative_index("beta_i", "K_i", K_i);
      current_statement__ = 84;
      stan::math::validate_non_negative_index("beta_s", "S", S);
      current_statement__ = 85;
      stan::math::validate_non_negative_index("beta_s", "S", S);
      current_statement__ = 86;
      stan::math::validate_non_negative_index("beta_s", "K_s", K_s);
      current_statement__ = 87;
      stan::math::validate_non_negative_index("beta_o", "S", S);
      current_statement__ = 88;
      stan::math::validate_non_negative_index("beta_o", "M", M);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("beta_o", "K_o", K_o);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (beta_i_raw_1dim__ * K_i) + (S * beta_s_raw_2dim__ *
      K_s) + (S * beta_o_raw_2dim__ * K_o);
  }
  inline std::string model_name() const final {
    return "model_nhmm_ccc";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_nhmm_ccc_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      current_statement__ = 1;
      beta_i_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
                     K_i);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      current_statement__ = 2;
      beta_s_raw = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(S,
                     beta_s_raw_2dim__, K_s);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_o_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_o_raw_2dim__,
            K_o, DUMMY_VAR__));
      current_statement__ = 3;
      beta_o_raw = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(S,
                     beta_o_raw_2dim__, K_o);
      local_scalar_t__ log_lik = DUMMY_VAR__;
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, K_i, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(beta_i,
        stan::math::append_row(zeros_row_K_i, beta_i_raw),
        "assigning variable beta_i");
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, K_s,
            DUMMY_VAR__));
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_o =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(M, K_o,
            DUMMY_VAR__));
      current_statement__ = 12;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 9;
        stan::model::assign(beta_s,
          stan::math::append_row(zeros_row_K_s,
            stan::model::rvalue(beta_s_raw, "beta_s_raw",
              stan::model::index_uni(s))), "assigning variable beta_s",
          stan::model::index_uni(s));
        current_statement__ = 10;
        stan::model::assign(beta_o,
          stan::math::append_row(zeros_row_K_o,
            stan::model::rvalue(beta_o_raw, "beta_o_raw",
              stan::model::index_uni(s))), "assigning variable beta_o",
          stan::model::index_uni(s));
      }
      local_scalar_t__ prior = DUMMY_VAR__;
      current_statement__ = 8;
      prior = stan::math::normal_lpdf<false>(
                stan::math::to_vector(beta_i_raw), 0, 5);
      current_statement__ = 16;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 13;
        prior = (prior +
          stan::math::normal_lpdf<false>(
            stan::math::to_vector(
              stan::model::rvalue(beta_s_raw, "beta_s_raw",
                stan::model::index_uni(s))), 0, 5));
        current_statement__ = 14;
        prior = (prior +
          stan::math::normal_lpdf<false>(
            stan::math::to_vector(
              stan::model::rvalue(beta_o_raw, "beta_o_raw",
                stan::model::index_uni(s))), 0, 5));
      }
      {
        current_statement__ = 17;
        stan::math::validate_non_negative_index("ll", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> ll =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 19;
        stan::math::validate_non_negative_index("log_Pi", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,1> log_Pi =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 21;
        stan::math::validate_non_negative_index("log_B", "S", S);
        current_statement__ = 22;
        stan::math::validate_non_negative_index("log_B", "M + 1", (M + 1));
        Eigen::Matrix<local_scalar_t__,-1,-1> log_B =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, (M + 1),
            DUMMY_VAR__);
        current_statement__ = 24;
        stan::math::validate_non_negative_index("log_py", "S", S);
        current_statement__ = 25;
        stan::math::validate_non_negative_index("log_py", "T", T);
        Eigen::Matrix<local_scalar_t__,-1,-1> log_py =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, T, DUMMY_VAR__);
        current_statement__ = 27;
        stan::math::validate_non_negative_index("log_A", "S", S);
        current_statement__ = 28;
        stan::math::validate_non_negative_index("log_A", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,-1> log_A =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, S, DUMMY_VAR__);
        current_statement__ = 30;
        stan::model::assign(log_Pi,
          stan::math::log_softmax(
            stan::model::rvalue(beta_i, "beta_i", stan::model::index_omni(),
              stan::model::index_uni(1))), "assigning variable log_Pi");
        current_statement__ = 33;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 31;
          stan::model::assign(log_A,
            stan::math::transpose(
              stan::math::log_softmax(
                stan::model::rvalue(beta_s, "beta_s",
                  stan::model::index_uni(s), stan::model::index_omni(),
                  stan::model::index_uni(1)))), "assigning variable log_A",
            stan::model::index_uni(s), stan::model::index_omni());
        }
        current_statement__ = 36;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 34;
          stan::model::assign(log_B,
            stan::math::transpose(
              stan::math::log_softmax(
                stan::model::rvalue(beta_o, "beta_o",
                  stan::model::index_uni(s), stan::model::index_omni(),
                  stan::model::index_uni(1)))), "assigning variable log_B",
            stan::model::index_uni(s), stan::model::index_min_max(1, M));
        }
        current_statement__ = 42;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 39;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 37;
            stan::model::assign(log_py,
              stan::model::rvalue(log_B, "log_B", stan::model::index_omni(),
                stan::model::index_uni(
                  stan::model::rvalue(obs, "obs", stan::model::index_uni(t),
                    stan::model::index_uni(i)))),
              "assigning variable log_py", stan::model::index_omni(),
              stan::model::index_uni(t));
          }
          current_statement__ = 40;
          stan::model::assign(ll, loglik(log_Pi, log_A, log_py, pstream__),
            "assigning variable ll", stan::model::index_uni(i));
        }
        current_statement__ = 43;
        log_lik = stan::math::sum(ll);
      }
      {
        current_statement__ = 45;
        lp_accum__.add(prior);
        current_statement__ = 46;
        lp_accum__.add(log_lik);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_nhmm_ccc_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,-1> beta_i_raw =
        Eigen::Matrix<double,-1,-1>::Constant(beta_i_raw_1dim__, K_i,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta_i_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
                     K_i);
      std::vector<Eigen::Matrix<double,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<double,-1,-1>>(S,
          Eigen::Matrix<double,-1,-1>::Constant(beta_s_raw_2dim__, K_s,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 2;
      beta_s_raw = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(S,
                     beta_s_raw_2dim__, K_s);
      std::vector<Eigen::Matrix<double,-1,-1>> beta_o_raw =
        std::vector<Eigen::Matrix<double,-1,-1>>(S,
          Eigen::Matrix<double,-1,-1>::Constant(beta_o_raw_2dim__, K_o,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 3;
      beta_o_raw = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(S,
                     beta_o_raw_2dim__, K_o);
      double log_lik = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,-1> beta_i =
        Eigen::Matrix<double,-1,-1>::Constant(S, K_i,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<Eigen::Matrix<double,-1,-1>> beta_s =
        std::vector<Eigen::Matrix<double,-1,-1>>(S,
          Eigen::Matrix<double,-1,-1>::Constant(S, K_s,
            std::numeric_limits<double>::quiet_NaN()));
      std::vector<Eigen::Matrix<double,-1,-1>> beta_o =
        std::vector<Eigen::Matrix<double,-1,-1>>(S,
          Eigen::Matrix<double,-1,-1>::Constant(M, K_o,
            std::numeric_limits<double>::quiet_NaN()));
      double prior = std::numeric_limits<double>::quiet_NaN();
      out__.write(beta_i_raw);
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            out__.write(stan::model::rvalue(beta_s_raw, "beta_s_raw",
                          stan::model::index_uni(sym3__),
                          stan::model::index_uni(sym2__),
                          stan::model::index_uni(sym1__)));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= beta_o_raw_2dim__; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            out__.write(stan::model::rvalue(beta_o_raw, "beta_o_raw",
                          stan::model::index_uni(sym3__),
                          stan::model::index_uni(sym2__),
                          stan::model::index_uni(sym1__)));
          }
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 5;
      stan::model::assign(beta_i,
        stan::math::append_row(zeros_row_K_i, beta_i_raw),
        "assigning variable beta_i");
      current_statement__ = 12;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 9;
        stan::model::assign(beta_s,
          stan::math::append_row(zeros_row_K_s,
            stan::model::rvalue(beta_s_raw, "beta_s_raw",
              stan::model::index_uni(s))), "assigning variable beta_s",
          stan::model::index_uni(s));
        current_statement__ = 10;
        stan::model::assign(beta_o,
          stan::math::append_row(zeros_row_K_o,
            stan::model::rvalue(beta_o_raw, "beta_o_raw",
              stan::model::index_uni(s))), "assigning variable beta_o",
          stan::model::index_uni(s));
      }
      current_statement__ = 8;
      prior = stan::math::normal_lpdf<false>(
                stan::math::to_vector(beta_i_raw), 0, 5);
      current_statement__ = 16;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 13;
        prior = (prior +
          stan::math::normal_lpdf<false>(
            stan::math::to_vector(
              stan::model::rvalue(beta_s_raw, "beta_s_raw",
                stan::model::index_uni(s))), 0, 5));
        current_statement__ = 14;
        prior = (prior +
          stan::math::normal_lpdf<false>(
            stan::math::to_vector(
              stan::model::rvalue(beta_o_raw, "beta_o_raw",
                stan::model::index_uni(s))), 0, 5));
      }
      {
        current_statement__ = 17;
        stan::math::validate_non_negative_index("ll", "N", N);
        Eigen::Matrix<double,-1,1> ll =
          Eigen::Matrix<double,-1,1>::Constant(N,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 19;
        stan::math::validate_non_negative_index("log_Pi", "S", S);
        Eigen::Matrix<double,-1,1> log_Pi =
          Eigen::Matrix<double,-1,1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 21;
        stan::math::validate_non_negative_index("log_B", "S", S);
        current_statement__ = 22;
        stan::math::validate_non_negative_index("log_B", "M + 1", (M + 1));
        Eigen::Matrix<double,-1,-1> log_B =
          Eigen::Matrix<double,-1,-1>::Constant(S, (M + 1),
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 24;
        stan::math::validate_non_negative_index("log_py", "S", S);
        current_statement__ = 25;
        stan::math::validate_non_negative_index("log_py", "T", T);
        Eigen::Matrix<double,-1,-1> log_py =
          Eigen::Matrix<double,-1,-1>::Constant(S, T,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 27;
        stan::math::validate_non_negative_index("log_A", "S", S);
        current_statement__ = 28;
        stan::math::validate_non_negative_index("log_A", "S", S);
        Eigen::Matrix<double,-1,-1> log_A =
          Eigen::Matrix<double,-1,-1>::Constant(S, S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 30;
        stan::model::assign(log_Pi,
          stan::math::log_softmax(
            stan::model::rvalue(beta_i, "beta_i", stan::model::index_omni(),
              stan::model::index_uni(1))), "assigning variable log_Pi");
        current_statement__ = 33;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 31;
          stan::model::assign(log_A,
            stan::math::transpose(
              stan::math::log_softmax(
                stan::model::rvalue(beta_s, "beta_s",
                  stan::model::index_uni(s), stan::model::index_omni(),
                  stan::model::index_uni(1)))), "assigning variable log_A",
            stan::model::index_uni(s), stan::model::index_omni());
        }
        current_statement__ = 36;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 34;
          stan::model::assign(log_B,
            stan::math::transpose(
              stan::math::log_softmax(
                stan::model::rvalue(beta_o, "beta_o",
                  stan::model::index_uni(s), stan::model::index_omni(),
                  stan::model::index_uni(1)))), "assigning variable log_B",
            stan::model::index_uni(s), stan::model::index_min_max(1, M));
        }
        current_statement__ = 42;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 39;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 37;
            stan::model::assign(log_py,
              stan::model::rvalue(log_B, "log_B", stan::model::index_omni(),
                stan::model::index_uni(
                  stan::model::rvalue(obs, "obs", stan::model::index_uni(t),
                    stan::model::index_uni(i)))),
              "assigning variable log_py", stan::model::index_omni(),
              stan::model::index_uni(t));
          }
          current_statement__ = 40;
          stan::model::assign(ll, loglik(log_Pi, log_A, log_py, pstream__),
            "assigning variable ll", stan::model::index_uni(i));
        }
        current_statement__ = 43;
        log_lik = stan::math::sum(ll);
      }
      if (emit_transformed_parameters__) {
        out__.write(log_lik);
        out__.write(beta_i);
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              out__.write(stan::model::rvalue(beta_s, "beta_s",
                            stan::model::index_uni(sym3__),
                            stan::model::index_uni(sym2__),
                            stan::model::index_uni(sym1__)));
            }
          }
        }
        for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              out__.write(stan::model::rvalue(beta_o, "beta_o",
                            stan::model::index_uni(sym3__),
                            stan::model::index_uni(sym2__),
                            stan::model::index_uni(sym1__)));
            }
          }
        }
        out__.write(prior);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta_i_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
          K_i), "assigning variable beta_i_raw");
      out__.write(beta_i_raw);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        current_statement__ = 2;
        for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
          current_statement__ = 2;
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            current_statement__ = 2;
            stan::model::assign(beta_s_raw, in__.read<local_scalar_t__>(),
              "assigning variable beta_s_raw",
              stan::model::index_uni(sym3__), stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write(beta_s_raw);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_o_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_o_raw_2dim__,
            K_o, DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
        current_statement__ = 3;
        for (int sym2__ = 1; sym2__ <= beta_o_raw_2dim__; ++sym2__) {
          current_statement__ = 3;
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            current_statement__ = 3;
            stan::model::assign(beta_o_raw, in__.read<local_scalar_t__>(),
              "assigning variable beta_o_raw",
              stan::model::index_uni(sym3__), stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write(beta_o_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta_i_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(beta_i_raw_1dim__),
          static_cast<size_t>(K_i)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_s_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(S),
          static_cast<size_t>(beta_s_raw_2dim__), static_cast<size_t>(K_s)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta_o_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(S),
          static_cast<size_t>(beta_o_raw_2dim__), static_cast<size_t>(K_o)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_i_raw_flat__;
        current_statement__ = 1;
        beta_i_raw_flat__ = context__.vals_r("beta_i_raw");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(beta_i_raw, beta_i_raw_flat__[(pos__ - 1)],
              "assigning variable beta_i_raw",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta_i_raw);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> beta_s_raw_flat__;
        current_statement__ = 2;
        beta_s_raw_flat__ = context__.vals_r("beta_s_raw");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
            current_statement__ = 2;
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              current_statement__ = 2;
              stan::model::assign(beta_s_raw, beta_s_raw_flat__[(pos__ - 1)],
                "assigning variable beta_s_raw",
                stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 2;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write(beta_s_raw);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_o_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_o_raw_2dim__,
            K_o, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> beta_o_raw_flat__;
        current_statement__ = 3;
        beta_o_raw_flat__ = context__.vals_r("beta_o_raw");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= beta_o_raw_2dim__; ++sym2__) {
            current_statement__ = 3;
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              current_statement__ = 3;
              stan::model::assign(beta_o_raw, beta_o_raw_flat__[(pos__ - 1)],
                "assigning variable beta_o_raw",
                stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 3;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write(beta_o_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta_i_raw", "beta_s_raw",
                "beta_o_raw"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"log_lik", "beta_i", "beta_s", "beta_o", "prior"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    beta_i_raw_1dim__),
                                                 static_cast<size_t>(K_i)},
                std::vector<size_t>{static_cast<size_t>(S),
                  static_cast<size_t>(beta_s_raw_2dim__),
                  static_cast<size_t>(K_s)},
                std::vector<size_t>{static_cast<size_t>(S),
                  static_cast<size_t>(beta_o_raw_2dim__),
                  static_cast<size_t>(K_o)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(K_i)},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(S), static_cast<size_t>(K_s)},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(M), static_cast<size_t>(K_o)},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta_i_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
          param_names__.emplace_back(std::string() + "beta_s_raw" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_o_raw_2dim__; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
          param_names__.emplace_back(std::string() + "beta_o_raw" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik");
      for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_i" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta_s" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta_o" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      param_names__.emplace_back(std::string() + "prior");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta_i_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
          param_names__.emplace_back(std::string() + "beta_s_raw" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_o_raw_2dim__; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
          param_names__.emplace_back(std::string() + "beta_o_raw" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik");
      for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_i" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta_s" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta_o" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      param_names__.emplace_back(std::string() + "prior");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_i_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_i_raw_1dim__) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"parameters\"},{\"name\":\"beta_s_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_s_raw_2dim__) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"parameters\"},{\"name\":\"beta_o_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_o_raw_2dim__) + ",\"cols\":" + std::to_string(K_o) + "}},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta_i\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_s\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"beta_o\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(M) + ",\"cols\":" + std::to_string(K_o) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"prior\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_i_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_i_raw_1dim__) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"parameters\"},{\"name\":\"beta_s_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_s_raw_2dim__) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"parameters\"},{\"name\":\"beta_o_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_o_raw_2dim__) + ",\"cols\":" + std::to_string(K_o) + "}},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta_i\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_s\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"beta_o\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(M) + ",\"cols\":" + std::to_string(K_o) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"prior\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((beta_i_raw_1dim__ * K_i) + ((S *
      beta_s_raw_2dim__) * K_s)) + ((S * beta_o_raw_2dim__) * K_o));
    const size_t num_transformed = emit_transformed_parameters * (((((1 + (S
      * K_i)) + ((S * S) * K_s)) + ((S * M) * K_o)) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((beta_i_raw_1dim__ * K_i) + ((S *
      beta_s_raw_2dim__) * K_s)) + ((S * beta_o_raw_2dim__) * K_o));
    const size_t num_transformed = emit_transformed_parameters * (((((1 + (S
      * K_i)) + ((S * S) * K_s)) + ((S * M) * K_o)) + 1));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_nhmm_ccc_namespace::model_nhmm_ccc;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_nhmm_ccc_namespace::profiles__;
}
#endif
#endif
