// Generated by rstantools.  Do not edit by hand.

/*
    seqHMM is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    seqHMM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with seqHMM.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_nhmm_ccc_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 91> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 47, column 0 to column 14)",
  " (in 'string', line 50, column 0 to column 22)",
  " (in 'string', line 53, column 0 to column 22)",
  " (in 'string', line 56, column 2 to column 16)",
  " (in 'string', line 57, column 2 to column 20)",
  " (in 'string', line 106, column 2 to column 22)",
  " (in 'string', line 107, column 2 to column 26)",
  " (in 'string', line 61, column 0 to column 48)",
  " (in 'string', line 65, column 2 to column 52)",
  " (in 'string', line 64, column 14 to line 66, column 1)",
  " (in 'string', line 64, column 0 to line 66, column 1)",
  " (in 'string', line 70, column 2 to column 52)",
  " (in 'string', line 69, column 15 to line 71, column 1)",
  " (in 'string', line 69, column 0 to line 71, column 1)",
  " (in 'string', line 73, column 11 to column 12)",
  " (in 'string', line 73, column 4 to column 17)",
  " (in 'string', line 74, column 11 to column 12)",
  " (in 'string', line 74, column 4 to column 21)",
  " (in 'string', line 75, column 11 to column 12)",
  " (in 'string', line 75, column 14 to column 15)",
  " (in 'string', line 75, column 4 to column 23)",
  " (in 'string', line 76, column 11 to column 12)",
  " (in 'string', line 76, column 14 to column 15)",
  " (in 'string', line 76, column 4 to column 24)",
  " (in 'string', line 77, column 11 to column 12)",
  " (in 'string', line 77, column 14 to column 15)",
  " (in 'string', line 77, column 4 to column 23)",
  " (in 'string', line 79, column 0 to column 17)",
  " (in 'string', line 82, column 2 to column 26)",
  " (in 'string', line 81, column 14 to line 83, column 1)",
  " (in 'string', line 81, column 0 to line 83, column 1)",
  " (in 'string', line 86, column 2 to column 26)",
  " (in 'string', line 85, column 14 to line 87, column 1)",
  " (in 'string', line 85, column 0 to line 87, column 1)",
  " (in 'string', line 93, column 10 to column 43)",
  " (in 'string', line 92, column 15 to line 94, column 9)",
  " (in 'string', line 91, column 10 to column 41)",
  " (in 'string', line 90, column 27 to line 92, column 9)",
  " (in 'string', line 90, column 8 to line 94, column 9)",
  " (in 'string', line 89, column 20 to line 95, column 7)",
  " (in 'string', line 89, column 6 to line 95, column 7)",
  " (in 'string', line 96, column 6 to column 44)",
  " (in 'string', line 88, column 18 to line 97, column 5)",
  " (in 'string', line 88, column 4 to line 97, column 5)",
  " (in 'string', line 98, column 4 to column 23)",
  " (in 'string', line 72, column 2 to line 99, column 3)",
  " (in 'string', line 102, column 2 to column 19)",
  " (in 'string', line 103, column 2 to column 21)",
  " (in 'string', line 38, column 0 to column 17)",
  " (in 'string', line 39, column 0 to column 17)",
  " (in 'string', line 40, column 0 to column 17)",
  " (in 'string', line 41, column 0 to column 17)",
  " (in 'string', line 42, column 6 to column 7)",
  " (in 'string', line 42, column 9 to column 10)",
  " (in 'string', line 42, column 0 to column 38)",
  " (in 'string', line 47, column 8 to column 9)",
  " (in 'string', line 50, column 6 to column 7)",
  " (in 'string', line 50, column 17 to column 18)",
  " (in 'string', line 53, column 6 to column 7)",
  " (in 'string', line 53, column 17 to column 18)",
  " (in 'string', line 7, column 2 to column 23)",
  " (in 'string', line 8, column 2 to column 23)",
  " (in 'string', line 9, column 9 to column 10)",
  " (in 'string', line 9, column 2 to column 22)",
  " (in 'string', line 10, column 9 to column 10)",
  " (in 'string', line 10, column 2 to column 26)",
  " (in 'string', line 11, column 2 to column 35)",
  " (in 'string', line 14, column 6 to column 79)",
  " (in 'string', line 13, column 19 to line 15, column 5)",
  " (in 'string', line 13, column 4 to line 15, column 5)",
  " (in 'string', line 16, column 4 to column 30)",
  " (in 'string', line 12, column 17 to line 17, column 3)",
  " (in 'string', line 12, column 2 to line 17, column 3)",
  " (in 'string', line 18, column 2 to column 32)",
  " (in 'string', line 6, column 64 to line 19, column 1)",
  " (in 'string', line 22, column 2 to column 23)",
  " (in 'string', line 23, column 2 to column 23)",
  " (in 'string', line 24, column 9 to column 10)",
  " (in 'string', line 24, column 2 to column 22)",
  " (in 'string', line 25, column 9 to column 10)",
  " (in 'string', line 25, column 2 to column 26)",
  " (in 'string', line 26, column 2 to column 35)",
  " (in 'string', line 29, column 6 to column 76)",
  " (in 'string', line 28, column 19 to line 30, column 5)",
  " (in 'string', line 28, column 4 to line 30, column 5)",
  " (in 'string', line 31, column 4 to column 30)",
  " (in 'string', line 27, column 17 to line 32, column 3)",
  " (in 'string', line 27, column 2 to line 32, column 3)",
  " (in 'string', line 33, column 2 to column 32)",
  " (in 'string', line 21, column 56 to line 34, column 1)"};
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, T1__, stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__,
       const std::vector<Eigen::Matrix<T1__,-1,-1>>& log_A, const T2__&
       log_py_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
  stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__, const T1__& log_A_arg__, const T2__&
       log_py_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, T1__, stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__,
       const std::vector<Eigen::Matrix<T1__,-1,-1>>& log_A, const T2__&
       log_py_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& log_Pi = stan::math::to_ref(log_Pi_arg__);
  const auto& log_py = stan::math::to_ref(log_py_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int S = std::numeric_limits<int>::min();
    current_statement__ = 61;
    S = stan::math::rows(log_py);
    int T = std::numeric_limits<int>::min();
    current_statement__ = 62;
    T = stan::math::cols(log_py);
    current_statement__ = 63;
    stan::math::validate_non_negative_index("log_alpha", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 65;
    stan::math::validate_non_negative_index("log_alpha_new", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 67;
    stan::model::assign(log_alpha,
      stan::math::add(log_Pi,
        stan::model::rvalue(log_py, "log_py", stan::model::index_omni(),
          stan::model::index_uni(1))), "assigning variable log_alpha");
    current_statement__ = 73;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 70;
      for (int k = 1; k <= S; ++k) {
        current_statement__ = 68;
        stan::model::assign(log_alpha_new,
          stan::math::log_sum_exp(
            stan::math::add(
              stan::math::add(log_alpha,
                stan::model::rvalue(log_A, "log_A",
                  stan::model::index_uni(t), stan::model::index_omni(),
                  stan::model::index_uni(k))),
              stan::model::rvalue(log_py, "log_py",
                stan::model::index_uni(k), stan::model::index_uni(t)))),
          "assigning variable log_alpha_new", stan::model::index_uni(k));
      }
      current_statement__ = 71;
      stan::model::assign(log_alpha, log_alpha_new,
        "assigning variable log_alpha");
    }
    current_statement__ = 74;
    return stan::math::log_sum_exp(log_alpha);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
  stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__, const T1__& log_A_arg__, const T2__&
       log_py_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& log_Pi = stan::math::to_ref(log_Pi_arg__);
  const auto& log_A = stan::math::to_ref(log_A_arg__);
  const auto& log_py = stan::math::to_ref(log_py_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int S = std::numeric_limits<int>::min();
    current_statement__ = 76;
    S = stan::math::rows(log_py);
    int T = std::numeric_limits<int>::min();
    current_statement__ = 77;
    T = stan::math::cols(log_py);
    current_statement__ = 78;
    stan::math::validate_non_negative_index("log_alpha", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 80;
    stan::math::validate_non_negative_index("log_alpha_new", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 82;
    stan::model::assign(log_alpha,
      stan::math::add(log_Pi,
        stan::model::rvalue(log_py, "log_py", stan::model::index_omni(),
          stan::model::index_uni(1))), "assigning variable log_alpha");
    current_statement__ = 88;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 85;
      for (int k = 1; k <= S; ++k) {
        current_statement__ = 83;
        stan::model::assign(log_alpha_new,
          stan::math::log_sum_exp(
            stan::math::add(
              stan::math::add(log_alpha,
                stan::model::rvalue(log_A, "log_A",
                  stan::model::index_omni(), stan::model::index_uni(k))),
              stan::model::rvalue(log_py, "log_py",
                stan::model::index_uni(k), stan::model::index_uni(t)))),
          "assigning variable log_alpha_new", stan::model::index_uni(k));
      }
      current_statement__ = 86;
      stan::model::assign(log_alpha, log_alpha_new,
        "assigning variable log_alpha");
    }
    current_statement__ = 89;
    return stan::math::log_sum_exp(log_alpha);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_nhmm_ccc final : public model_base_crtp<model_nhmm_ccc> {
private:
  int N;
  int T;
  int M;
  int S;
  std::vector<std::vector<int>> obs;
public:
  ~model_nhmm_ccc() {}
  model_nhmm_ccc(stan::io::var_context& context__, unsigned int
                 random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_nhmm_ccc_namespace::model_nhmm_ccc";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 49;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 49;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 50;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 51;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 51;
      stan::math::check_greater_or_equal(function__, "M", M, 2);
      current_statement__ = 52;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 52;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("obs", "T", T);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("obs", "N", N);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "obs", "int",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(N)});
      obs = std::vector<std::vector<int>>(T,
              std::vector<int>(N, std::numeric_limits<int>::min()));
      {
        std::vector<int> obs_flat__;
        current_statement__ = 55;
        obs_flat__ = context__.vals_i("obs");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 55;
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            current_statement__ = 55;
            stan::model::assign(obs, obs_flat__[(pos__ - 1)],
              "assigning variable obs", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 55;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 55;
      stan::math::check_greater_or_equal(function__, "obs", obs, 0);
      current_statement__ = 55;
      stan::math::check_less_or_equal(function__, "obs", obs, M);
      current_statement__ = 56;
      stan::math::validate_positive_index("Pi", "S", S);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("A", "S", S);
      current_statement__ = 58;
      stan::math::validate_positive_index("A", "S", S);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("B", "S", S);
      current_statement__ = 60;
      stan::math::validate_positive_index("B", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (S - 1) + (S * (S - 1)) + (S * (M - 1));
  }
  inline std::string model_name() const final {
    return "model_nhmm_ccc";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_nhmm_ccc_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> Pi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 1;
      Pi = in__.template read_constrain_simplex<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, S);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> A =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__));
      current_statement__ = 2;
      A = in__.template read_constrain_simplex<
            std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
            jacobian__>(lp__, S, S);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> B =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__));
      current_statement__ = 3;
      B = in__.template read_constrain_simplex<
            std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
            jacobian__>(lp__, S, M);
      local_scalar_t__ log_lik_ = DUMMY_VAR__;
      local_scalar_t__ prior_ = DUMMY_VAR__;
      current_statement__ = 5;
      prior_ = 0.0;
      current_statement__ = 8;
      prior_ = (prior_ +
        stan::math::dirichlet_lpdf<false>(Pi, stan::math::rep_vector(2, S)));
      current_statement__ = 11;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 9;
        prior_ = (prior_ +
          stan::math::dirichlet_lpdf<false>(
            stan::model::rvalue(A, "A", stan::model::index_uni(s)),
            stan::math::rep_vector(2, S)));
      }
      current_statement__ = 14;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 12;
        prior_ = (prior_ +
          stan::math::dirichlet_lpdf<false>(
            stan::model::rvalue(B, "B", stan::model::index_uni(s)),
            stan::math::rep_vector(2, M)));
      }
      {
        current_statement__ = 15;
        stan::math::validate_non_negative_index("ll", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> ll =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 17;
        stan::math::validate_non_negative_index("log_Pi", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,1> log_Pi =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 19;
        stan::math::validate_non_negative_index("log_B", "S", S);
        current_statement__ = 20;
        stan::math::validate_non_negative_index("log_B", "M", M);
        Eigen::Matrix<local_scalar_t__,-1,-1> log_B =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, M, DUMMY_VAR__);
        current_statement__ = 22;
        stan::math::validate_non_negative_index("log_py", "S", S);
        current_statement__ = 23;
        stan::math::validate_non_negative_index("log_py", "T", T);
        Eigen::Matrix<local_scalar_t__,-1,-1> log_py =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, T, DUMMY_VAR__);
        current_statement__ = 25;
        stan::math::validate_non_negative_index("log_A", "S", S);
        current_statement__ = 26;
        stan::math::validate_non_negative_index("log_A", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,-1> log_A =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, S, DUMMY_VAR__);
        current_statement__ = 28;
        stan::model::assign(log_Pi, stan::math::log(Pi),
          "assigning variable log_Pi");
        current_statement__ = 31;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 29;
          stan::model::assign(log_A,
            stan::math::log(
              stan::math::transpose(
                stan::model::rvalue(A, "A", stan::model::index_uni(s)))),
            "assigning variable log_A", stan::model::index_uni(s),
            stan::model::index_omni());
        }
        current_statement__ = 34;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 32;
          stan::model::assign(log_B,
            stan::math::log(
              stan::math::transpose(
                stan::model::rvalue(B, "B", stan::model::index_uni(s)))),
            "assigning variable log_B", stan::model::index_uni(s),
            stan::model::index_omni());
        }
        current_statement__ = 44;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 41;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 39;
            if (stan::math::logical_eq(
                  stan::model::rvalue(obs, "obs", stan::model::index_uni(t),
                    stan::model::index_uni(i)), 0)) {
              current_statement__ = 37;
              stan::model::assign(log_py, stan::math::rep_vector(0, S),
                "assigning variable log_py", stan::model::index_omni(),
                stan::model::index_uni(t));
            } else {
              current_statement__ = 35;
              stan::model::assign(log_py,
                stan::model::rvalue(log_B, "log_B",
                  stan::model::index_omni(),
                  stan::model::index_uni(
                    stan::model::rvalue(obs, "obs",
                      stan::model::index_uni(t), stan::model::index_uni(i)))),
                "assigning variable log_py", stan::model::index_omni(),
                stan::model::index_uni(t));
            }
          }
          current_statement__ = 42;
          stan::model::assign(ll, loglik(log_Pi, log_A, log_py, pstream__),
            "assigning variable ll", stan::model::index_uni(i));
        }
        current_statement__ = 45;
        log_lik_ = stan::math::sum(ll);
      }
      {
        current_statement__ = 47;
        lp_accum__.add(prior_);
        current_statement__ = 48;
        lp_accum__.add(log_lik_);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_nhmm_ccc_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> Pi =
        Eigen::Matrix<double,-1,1>::Constant(S,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      Pi = in__.template read_constrain_simplex<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, S);
      std::vector<Eigen::Matrix<double,-1,1>> A =
        std::vector<Eigen::Matrix<double,-1,1>>(S,
          Eigen::Matrix<double,-1,1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 2;
      A = in__.template read_constrain_simplex<
            std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
            jacobian__>(lp__, S, S);
      std::vector<Eigen::Matrix<double,-1,1>> B =
        std::vector<Eigen::Matrix<double,-1,1>>(S,
          Eigen::Matrix<double,-1,1>::Constant(M,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 3;
      B = in__.template read_constrain_simplex<
            std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
            jacobian__>(lp__, S, M);
      double log_lik_ = std::numeric_limits<double>::quiet_NaN();
      double prior_ = std::numeric_limits<double>::quiet_NaN();
      out__.write(Pi);
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          out__.write(A[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          out__.write(B[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 5;
      prior_ = 0.0;
      current_statement__ = 8;
      prior_ = (prior_ +
        stan::math::dirichlet_lpdf<false>(Pi, stan::math::rep_vector(2, S)));
      current_statement__ = 11;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 9;
        prior_ = (prior_ +
          stan::math::dirichlet_lpdf<false>(
            stan::model::rvalue(A, "A", stan::model::index_uni(s)),
            stan::math::rep_vector(2, S)));
      }
      current_statement__ = 14;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 12;
        prior_ = (prior_ +
          stan::math::dirichlet_lpdf<false>(
            stan::model::rvalue(B, "B", stan::model::index_uni(s)),
            stan::math::rep_vector(2, M)));
      }
      {
        current_statement__ = 15;
        stan::math::validate_non_negative_index("ll", "N", N);
        Eigen::Matrix<double,-1,1> ll =
          Eigen::Matrix<double,-1,1>::Constant(N,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 17;
        stan::math::validate_non_negative_index("log_Pi", "S", S);
        Eigen::Matrix<double,-1,1> log_Pi =
          Eigen::Matrix<double,-1,1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 19;
        stan::math::validate_non_negative_index("log_B", "S", S);
        current_statement__ = 20;
        stan::math::validate_non_negative_index("log_B", "M", M);
        Eigen::Matrix<double,-1,-1> log_B =
          Eigen::Matrix<double,-1,-1>::Constant(S, M,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 22;
        stan::math::validate_non_negative_index("log_py", "S", S);
        current_statement__ = 23;
        stan::math::validate_non_negative_index("log_py", "T", T);
        Eigen::Matrix<double,-1,-1> log_py =
          Eigen::Matrix<double,-1,-1>::Constant(S, T,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 25;
        stan::math::validate_non_negative_index("log_A", "S", S);
        current_statement__ = 26;
        stan::math::validate_non_negative_index("log_A", "S", S);
        Eigen::Matrix<double,-1,-1> log_A =
          Eigen::Matrix<double,-1,-1>::Constant(S, S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 28;
        stan::model::assign(log_Pi, stan::math::log(Pi),
          "assigning variable log_Pi");
        current_statement__ = 31;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 29;
          stan::model::assign(log_A,
            stan::math::log(
              stan::math::transpose(
                stan::model::rvalue(A, "A", stan::model::index_uni(s)))),
            "assigning variable log_A", stan::model::index_uni(s),
            stan::model::index_omni());
        }
        current_statement__ = 34;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 32;
          stan::model::assign(log_B,
            stan::math::log(
              stan::math::transpose(
                stan::model::rvalue(B, "B", stan::model::index_uni(s)))),
            "assigning variable log_B", stan::model::index_uni(s),
            stan::model::index_omni());
        }
        current_statement__ = 44;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 41;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 39;
            if (stan::math::logical_eq(
                  stan::model::rvalue(obs, "obs", stan::model::index_uni(t),
                    stan::model::index_uni(i)), 0)) {
              current_statement__ = 37;
              stan::model::assign(log_py, stan::math::rep_vector(0, S),
                "assigning variable log_py", stan::model::index_omni(),
                stan::model::index_uni(t));
            } else {
              current_statement__ = 35;
              stan::model::assign(log_py,
                stan::model::rvalue(log_B, "log_B",
                  stan::model::index_omni(),
                  stan::model::index_uni(
                    stan::model::rvalue(obs, "obs",
                      stan::model::index_uni(t), stan::model::index_uni(i)))),
                "assigning variable log_py", stan::model::index_omni(),
                stan::model::index_uni(t));
            }
          }
          current_statement__ = 42;
          stan::model::assign(ll, loglik(log_Pi, log_A, log_py, pstream__),
            "assigning variable ll", stan::model::index_uni(i));
        }
        current_statement__ = 45;
        log_lik_ = stan::math::sum(ll);
      }
      if (emit_transformed_parameters__) {
        out__.write(log_lik_);
        out__.write(prior_);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double prior = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      prior = prior_;
      double log_lik = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      log_lik = log_lik_;
      out__.write(prior);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> Pi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(Pi,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(S),
        "assigning variable Pi");
      out__.write_free_simplex(Pi);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> A =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__));
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        current_statement__ = 2;
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          current_statement__ = 2;
          stan::model::assign(A, in__.read<local_scalar_t__>(),
            "assigning variable A", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_simplex(A);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> B =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 3;
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          current_statement__ = 3;
          stan::model::assign(B, in__.read<local_scalar_t__>(),
            "assigning variable B", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_simplex(B);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "Pi", "double",
        std::vector<size_t>{static_cast<size_t>(S)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "A", "double",
        std::vector<size_t>{static_cast<size_t>(S), static_cast<size_t>(S)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "B", "double",
        std::vector<size_t>{static_cast<size_t>(S), static_cast<size_t>(M)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> Pi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> Pi_flat__;
        current_statement__ = 1;
        Pi_flat__ = context__.vals_r("Pi");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(Pi, Pi_flat__[(pos__ - 1)],
            "assigning variable Pi", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(Pi);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> A =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> A_flat__;
        current_statement__ = 2;
        A_flat__ = context__.vals_r("A");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
            current_statement__ = 2;
            stan::model::assign(A, A_flat__[(pos__ - 1)],
              "assigning variable A", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_simplex(A);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> B =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> B_flat__;
        current_statement__ = 3;
        B_flat__ = context__.vals_r("B");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
            current_statement__ = 3;
            stan::model::assign(B, B_flat__[(pos__ - 1)],
              "assigning variable B", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 3;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_simplex(B);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"Pi", "A", "B"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"log_lik_", "prior_"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"prior", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(S)},
                std::vector<size_t>{static_cast<size_t>(S),
                  static_cast<size_t>(S)},
                std::vector<size_t>{static_cast<size_t>(S),
                  static_cast<size_t>(M)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
      param_names__.emplace_back(std::string() + "Pi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
        param_names__.emplace_back(std::string() + "A" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
        param_names__.emplace_back(std::string() + "B" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik_");
      param_names__.emplace_back(std::string() + "prior_");
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "prior");
      param_names__.emplace_back(std::string() + "log_lik");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= (S - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "Pi" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= (S - 1); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
        param_names__.emplace_back(std::string() + "A" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= (M - 1); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
        param_names__.emplace_back(std::string() + "B" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik_");
      param_names__.emplace_back(std::string() + "prior_");
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "prior");
      param_names__.emplace_back(std::string() + "log_lik");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"Pi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"parameters\"},{\"name\":\"A\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "}},\"block\":\"parameters\"},{\"name\":\"B\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "}},\"block\":\"parameters\"},{\"name\":\"log_lik_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"Pi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((S -1)) + "},\"block\":\"parameters\"},{\"name\":\"A\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((S -1)) + "}},\"block\":\"parameters\"},{\"name\":\"B\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((M -1)) + "}},\"block\":\"parameters\"},{\"name\":\"log_lik_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((S + (S * S)) + (S * M));
    const size_t num_transformed = emit_transformed_parameters * ((1 + 1));
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((S + (S * S)) + (S * M));
    const size_t num_transformed = emit_transformed_parameters * ((1 + 1));
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_nhmm_ccc_namespace::model_nhmm_ccc;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_nhmm_ccc_namespace::profiles__;
}
#endif
#endif
