// Generated by rstantools.  Do not edit by hand.

/*
    seqHMM is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    seqHMM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with seqHMM.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_multichannel_nhmm_vvc_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 129> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 54, column 0 to column 36)",
  " (in 'string', line 55, column 0 to column 30)",
  " (in 'string', line 58, column 0 to column 39)",
  " (in 'string', line 61, column 0 to column 25)",
  " (in 'string', line 64, column 2 to column 16)",
  " (in 'string', line 65, column 2 to column 20)",
  " (in 'string', line 67, column 0 to column 56)",
  " (in 'string', line 68, column 0 to column 71)",
  " (in 'string', line 70, column 0 to column 31)",
  " (in 'string', line 128, column 2 to column 22)",
  " (in 'string', line 129, column 2 to column 26)",
  " (in 'string', line 72, column 2 to column 64)",
  " (in 'string', line 71, column 14 to line 73, column 1)",
  " (in 'string', line 71, column 0 to line 73, column 1)",
  " (in 'string', line 76, column 0 to column 42)",
  " (in 'string', line 77, column 0 to column 52)",
  " (in 'string', line 81, column 2 to column 57)",
  " (in 'string', line 80, column 14 to line 82, column 1)",
  " (in 'string', line 80, column 0 to line 82, column 1)",
  " (in 'string', line 87, column 4 to column 57)",
  " (in 'string', line 86, column 17 to line 88, column 3)",
  " (in 'string', line 86, column 2 to line 88, column 3)",
  " (in 'string', line 85, column 15 to line 89, column 1)",
  " (in 'string', line 85, column 0 to line 89, column 1)",
  " (in 'string', line 91, column 11 to column 12)",
  " (in 'string', line 91, column 4 to column 17)",
  " (in 'string', line 92, column 11 to column 12)",
  " (in 'string', line 92, column 4 to column 21)",
  " (in 'string', line 93, column 10 to column 11)",
  " (in 'string', line 93, column 20 to column 21)",
  " (in 'string', line 93, column 23 to column 24)",
  " (in 'string', line 93, column 4 to column 32)",
  " (in 'string', line 94, column 11 to column 12)",
  " (in 'string', line 94, column 14 to column 15)",
  " (in 'string', line 94, column 4 to column 24)",
  " (in 'string', line 95, column 10 to column 11)",
  " (in 'string', line 95, column 20 to column 21)",
  " (in 'string', line 95, column 23 to column 24)",
  " (in 'string', line 95, column 4 to column 32)",
  " (in 'string', line 99, column 4 to column 34)",
  " (in 'string', line 98, column 17 to line 100, column 3)",
  " (in 'string', line 98, column 2 to line 100, column 3)",
  " (in 'string', line 97, column 15 to line 101, column 1)",
  " (in 'string', line 97, column 0 to line 101, column 1)",
  " (in 'string', line 102, column 11 to column 12)",
  " (in 'string', line 102, column 4 to column 39)",
  " (in 'string', line 105, column 0 to column 48)",
  " (in 'string', line 109, column 2 to column 54)",
  " (in 'string', line 108, column 14 to line 110, column 1)",
  " (in 'string', line 108, column 0 to line 110, column 1)",
  " (in 'string', line 111, column 8 to column 28)",
  " (in 'string', line 114, column 12 to column 52)",
  " (in 'string', line 113, column 31 to line 115, column 11)",
  " (in 'string', line 113, column 10 to line 115, column 11)",
  " (in 'string', line 112, column 22 to line 116, column 9)",
  " (in 'string', line 112, column 8 to line 116, column 9)",
  " (in 'string', line 106, column 20 to line 117, column 7)",
  " (in 'string', line 106, column 6 to line 117, column 7)",
  " (in 'string', line 118, column 6 to column 44)",
  " (in 'string', line 103, column 18 to line 119, column 5)",
  " (in 'string', line 103, column 4 to line 119, column 5)",
  " (in 'string', line 120, column 4 to column 23)",
  " (in 'string', line 90, column 2 to line 121, column 3)",
  " (in 'string', line 124, column 2 to column 19)",
  " (in 'string', line 125, column 2 to column 21)",
  " (in 'string', line 38, column 0 to column 15)",
  " (in 'string', line 39, column 0 to column 15)",
  " (in 'string', line 40, column 0 to column 15)",
  " (in 'string', line 41, column 0 to column 15)",
  " (in 'string', line 42, column 0 to column 15)",
  " (in 'string', line 43, column 6 to column 7)",
  " (in 'string', line 43, column 9 to column 10)",
  " (in 'string', line 43, column 12 to column 13)",
  " (in 'string', line 43, column 0 to column 40)",
  " (in 'string', line 45, column 0 to column 17)",
  " (in 'string', line 46, column 6 to column 7)",
  " (in 'string', line 46, column 16 to column 19)",
  " (in 'string', line 46, column 0 to column 25)",
  " (in 'string', line 48, column 0 to column 17)",
  " (in 'string', line 49, column 6 to column 7)",
  " (in 'string', line 49, column 9 to column 10)",
  " (in 'string', line 49, column 19 to column 22)",
  " (in 'string', line 49, column 0 to column 28)",
  " (in 'string', line 54, column 17 to column 22)",
  " (in 'string', line 55, column 7 to column 12)",
  " (in 'string', line 55, column 14 to column 17)",
  " (in 'string', line 58, column 6 to column 7)",
  " (in 'string', line 58, column 16 to column 21)",
  " (in 'string', line 58, column 23 to column 26)",
  " (in 'string', line 61, column 6 to column 7)",
  " (in 'string', line 61, column 9 to column 10)",
  " (in 'string', line 61, column 20 to column 21)",
  " (in 'string', line 67, column 7 to column 8)",
  " (in 'string', line 68, column 7 to column 8)",
  " (in 'string', line 68, column 10 to column 13)",
  " (in 'string', line 70, column 6 to column 7)",
  " (in 'string', line 70, column 16 to column 17)",
  " (in 'string', line 70, column 19 to column 22)",
  " (in 'string', line 7, column 2 to column 23)",
  " (in 'string', line 8, column 2 to column 23)",
  " (in 'string', line 9, column 9 to column 10)",
  " (in 'string', line 9, column 2 to column 22)",
  " (in 'string', line 10, column 9 to column 10)",
  " (in 'string', line 10, column 2 to column 26)",
  " (in 'string', line 11, column 2 to column 35)",
  " (in 'string', line 14, column 6 to column 79)",
  " (in 'string', line 13, column 19 to line 15, column 5)",
  " (in 'string', line 13, column 4 to line 15, column 5)",
  " (in 'string', line 16, column 4 to column 30)",
  " (in 'string', line 12, column 17 to line 17, column 3)",
  " (in 'string', line 12, column 2 to line 17, column 3)",
  " (in 'string', line 18, column 2 to column 32)",
  " (in 'string', line 6, column 64 to line 19, column 1)",
  " (in 'string', line 22, column 2 to column 23)",
  " (in 'string', line 23, column 2 to column 23)",
  " (in 'string', line 24, column 9 to column 10)",
  " (in 'string', line 24, column 2 to column 22)",
  " (in 'string', line 25, column 9 to column 10)",
  " (in 'string', line 25, column 2 to column 26)",
  " (in 'string', line 26, column 2 to column 35)",
  " (in 'string', line 29, column 6 to column 76)",
  " (in 'string', line 28, column 19 to line 30, column 5)",
  " (in 'string', line 28, column 4 to line 30, column 5)",
  " (in 'string', line 31, column 4 to column 30)",
  " (in 'string', line 27, column 17 to line 32, column 3)",
  " (in 'string', line 27, column 2 to line 32, column 3)",
  " (in 'string', line 33, column 2 to column 32)",
  " (in 'string', line 21, column 56 to line 34, column 1)"};
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, T1__, stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__,
       const std::vector<Eigen::Matrix<T1__,-1,-1>>& log_A, const T2__&
       log_py_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
  stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__, const T1__& log_A_arg__, const T2__&
       log_py_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, T1__, stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__,
       const std::vector<Eigen::Matrix<T1__,-1,-1>>& log_A, const T2__&
       log_py_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& log_Pi = stan::math::to_ref(log_Pi_arg__);
  const auto& log_py = stan::math::to_ref(log_py_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int S = std::numeric_limits<int>::min();
    current_statement__ = 99;
    S = stan::math::rows(log_py);
    int T = std::numeric_limits<int>::min();
    current_statement__ = 100;
    T = stan::math::cols(log_py);
    current_statement__ = 101;
    stan::math::validate_non_negative_index("log_alpha", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 103;
    stan::math::validate_non_negative_index("log_alpha_new", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 105;
    stan::model::assign(log_alpha,
      stan::math::add(log_Pi,
        stan::model::rvalue(log_py, "log_py", stan::model::index_omni(),
          stan::model::index_uni(1))), "assigning variable log_alpha");
    current_statement__ = 111;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 108;
      for (int k = 1; k <= S; ++k) {
        current_statement__ = 106;
        stan::model::assign(log_alpha_new,
          stan::math::log_sum_exp(
            stan::math::add(
              stan::math::add(log_alpha,
                stan::model::rvalue(log_A, "log_A",
                  stan::model::index_uni(t), stan::model::index_omni(),
                  stan::model::index_uni(k))),
              stan::model::rvalue(log_py, "log_py",
                stan::model::index_uni(k), stan::model::index_uni(t)))),
          "assigning variable log_alpha_new", stan::model::index_uni(k));
      }
      current_statement__ = 109;
      stan::model::assign(log_alpha, log_alpha_new,
        "assigning variable log_alpha");
    }
    current_statement__ = 112;
    return stan::math::log_sum_exp(log_alpha);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
  stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__, const T1__& log_A_arg__, const T2__&
       log_py_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& log_Pi = stan::math::to_ref(log_Pi_arg__);
  const auto& log_A = stan::math::to_ref(log_A_arg__);
  const auto& log_py = stan::math::to_ref(log_py_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int S = std::numeric_limits<int>::min();
    current_statement__ = 114;
    S = stan::math::rows(log_py);
    int T = std::numeric_limits<int>::min();
    current_statement__ = 115;
    T = stan::math::cols(log_py);
    current_statement__ = 116;
    stan::math::validate_non_negative_index("log_alpha", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 118;
    stan::math::validate_non_negative_index("log_alpha_new", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 120;
    stan::model::assign(log_alpha,
      stan::math::add(log_Pi,
        stan::model::rvalue(log_py, "log_py", stan::model::index_omni(),
          stan::model::index_uni(1))), "assigning variable log_alpha");
    current_statement__ = 126;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 123;
      for (int k = 1; k <= S; ++k) {
        current_statement__ = 121;
        stan::model::assign(log_alpha_new,
          stan::math::log_sum_exp(
            stan::math::add(
              stan::math::add(log_alpha,
                stan::model::rvalue(log_A, "log_A",
                  stan::model::index_omni(), stan::model::index_uni(k))),
              stan::model::rvalue(log_py, "log_py",
                stan::model::index_uni(k), stan::model::index_uni(t)))),
          "assigning variable log_alpha_new", stan::model::index_uni(k));
      }
      current_statement__ = 124;
      stan::model::assign(log_alpha, log_alpha_new,
        "assigning variable log_alpha");
    }
    current_statement__ = 127;
    return stan::math::log_sum_exp(log_alpha);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_multichannel_nhmm_vvc final : public model_base_crtp<model_multichannel_nhmm_vvc> {
private:
  int N;
  int T;
  int M;
  int S;
  int C;
  std::vector<std::vector<std::vector<int>>> obs;
  int K_i;
  std::vector<Eigen::Matrix<double,-1,1>> X_i;
  int K_s;
  std::vector<std::vector<Eigen::Matrix<double,-1,1>>> X_s;
  int alpha_i_raw_1dim__;
  int beta_i_raw_1dim__;
  int beta_s_raw_2dim__;
public:
  ~model_multichannel_nhmm_vvc() {}
  model_multichannel_nhmm_vvc(stan::io::var_context& context__, unsigned int
                              random_seed__ = 0, std::ostream*
                              pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_multichannel_nhmm_vvc_namespace::model_multichannel_nhmm_vvc";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 66;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 66;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 66;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 67;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 67;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 67;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 68;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 68;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 68;
      stan::math::check_greater_or_equal(function__, "M", M, 2);
      current_statement__ = 69;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 69;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 69;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 70;
      context__.validate_dims("data initialization", "C", "int",
        std::vector<size_t>{});
      C = std::numeric_limits<int>::min();
      current_statement__ = 70;
      C = context__.vals_i("C")[(1 - 1)];
      current_statement__ = 70;
      stan::math::check_greater_or_equal(function__, "C", C, 2);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("obs", "C", C);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("obs", "T", T);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("obs", "N", N);
      current_statement__ = 74;
      context__.validate_dims("data initialization", "obs", "int",
        std::vector<size_t>{static_cast<size_t>(C), static_cast<size_t>(T),
          static_cast<size_t>(N)});
      obs = std::vector<std::vector<std::vector<int>>>(C,
              std::vector<std::vector<int>>(T,
                std::vector<int>(N, std::numeric_limits<int>::min())));
      {
        std::vector<int> obs_flat__;
        current_statement__ = 74;
        obs_flat__ = context__.vals_i("obs");
        current_statement__ = 74;
        pos__ = 1;
        current_statement__ = 74;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 74;
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            current_statement__ = 74;
            for (int sym3__ = 1; sym3__ <= C; ++sym3__) {
              current_statement__ = 74;
              stan::model::assign(obs, obs_flat__[(pos__ - 1)],
                "assigning variable obs", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 74;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 74;
      stan::math::check_greater_or_equal(function__, "obs", obs, 0);
      current_statement__ = 74;
      stan::math::check_less_or_equal(function__, "obs", obs, M);
      current_statement__ = 75;
      context__.validate_dims("data initialization", "K_i", "int",
        std::vector<size_t>{});
      K_i = std::numeric_limits<int>::min();
      current_statement__ = 75;
      K_i = context__.vals_i("K_i")[(1 - 1)];
      current_statement__ = 75;
      stan::math::check_greater_or_equal(function__, "K_i", K_i, 1);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("X_i", "N", N);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("X_i", "K_i", K_i);
      current_statement__ = 78;
      context__.validate_dims("data initialization", "X_i", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K_i)});
      X_i = std::vector<Eigen::Matrix<double,-1,1>>(N,
              Eigen::Matrix<double,-1,1>::Constant(K_i,
                std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> X_i_flat__;
        current_statement__ = 78;
        X_i_flat__ = context__.vals_r("X_i");
        current_statement__ = 78;
        pos__ = 1;
        current_statement__ = 78;
        for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
          current_statement__ = 78;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 78;
            stan::model::assign(X_i, X_i_flat__[(pos__ - 1)],
              "assigning variable X_i", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 78;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 79;
      context__.validate_dims("data initialization", "K_s", "int",
        std::vector<size_t>{});
      K_s = std::numeric_limits<int>::min();
      current_statement__ = 79;
      K_s = context__.vals_i("K_s")[(1 - 1)];
      current_statement__ = 79;
      stan::math::check_greater_or_equal(function__, "K_s", K_s, 1);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("X_s", "T", T);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("X_s", "N", N);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("X_s", "K_s", K_s);
      current_statement__ = 83;
      context__.validate_dims("data initialization", "X_s", "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(N),
          static_cast<size_t>(K_s)});
      X_s = std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(T,
              std::vector<Eigen::Matrix<double,-1,1>>(N,
                Eigen::Matrix<double,-1,1>::Constant(K_s,
                  std::numeric_limits<double>::quiet_NaN())));
      {
        std::vector<local_scalar_t__> X_s_flat__;
        current_statement__ = 83;
        X_s_flat__ = context__.vals_r("X_s");
        current_statement__ = 83;
        pos__ = 1;
        current_statement__ = 83;
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          current_statement__ = 83;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 83;
            for (int sym3__ = 1; sym3__ <= T; ++sym3__) {
              current_statement__ = 83;
              stan::model::assign(X_s, X_s_flat__[(pos__ - 1)],
                "assigning variable X_s", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 83;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 84;
      alpha_i_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 84;
      alpha_i_raw_1dim__ = (S - 1);
      current_statement__ = 84;
      stan::math::validate_non_negative_index("alpha_i_raw", "S - 1",
        alpha_i_raw_1dim__);
      current_statement__ = 85;
      beta_i_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 85;
      beta_i_raw_1dim__ = (S - 1);
      current_statement__ = 85;
      stan::math::validate_non_negative_index("beta_i_raw", "S - 1",
        beta_i_raw_1dim__);
      current_statement__ = 86;
      stan::math::validate_non_negative_index("beta_i_raw", "K_i", K_i);
      current_statement__ = 87;
      stan::math::validate_non_negative_index("beta_s_raw", "S", S);
      current_statement__ = 88;
      beta_s_raw_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 88;
      beta_s_raw_2dim__ = (S - 1);
      current_statement__ = 88;
      stan::math::validate_non_negative_index("beta_s_raw", "S - 1",
        beta_s_raw_2dim__);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("beta_s_raw", "K_s", K_s);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("B", "C", C);
      current_statement__ = 91;
      stan::math::validate_non_negative_index("B", "S", S);
      current_statement__ = 92;
      stan::math::validate_positive_index("B", "M", M);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("alpha_i", "S", S);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("beta_i", "S", S);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("beta_i", "K_i", K_i);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("beta_s", "S", S);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("beta_s", "S", S);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("beta_s", "K_s", K_s);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = alpha_i_raw_1dim__ + (beta_i_raw_1dim__ * K_i) + (S *
      beta_s_raw_2dim__ * K_s) + (C * S * (M - 1));
  }
  inline std::string model_name() const final {
    return "model_multichannel_nhmm_vvc";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_multichannel_nhmm_vvc_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(alpha_i_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      alpha_i_raw = in__.template read_constrain_positive_ordered<
                      Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
                      alpha_i_raw_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      current_statement__ = 2;
      beta_i_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
                     K_i);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      current_statement__ = 3;
      beta_s_raw = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(S,
                     beta_s_raw_2dim__, K_s);
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> B =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(C,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__)));
      current_statement__ = 4;
      B = in__.template read_constrain_simplex<
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>,
            jacobian__>(lp__, C, S, M);
      local_scalar_t__ log_lik_ = DUMMY_VAR__;
      local_scalar_t__ prior_ = DUMMY_VAR__;
      current_statement__ = 6;
      prior_ = 0.0;
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_i =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(alpha_i,
        stan::math::reverse(stan::math::append_row(0, alpha_i_raw)),
        "assigning variable alpha_i");
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, K_i, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(beta_i,
        stan::math::append_row(stan::math::rep_row_vector(0, K_i), beta_i_raw),
        "assigning variable beta_i");
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, K_s,
            DUMMY_VAR__));
      current_statement__ = 14;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 12;
        stan::model::assign(beta_s,
          stan::math::append_row(stan::math::rep_row_vector(0, K_s),
            stan::model::rvalue(beta_s_raw, "beta_s_raw",
              stan::model::index_uni(s))), "assigning variable beta_s",
          stan::model::index_uni(s));
      }
      current_statement__ = 15;
      prior_ = (prior_ + stan::math::normal_lpdf<false>(alpha_i_raw, 0, 5));
      current_statement__ = 16;
      prior_ = (prior_ +
        stan::math::normal_lpdf<false>(stan::math::to_vector(beta_i_raw), 0,
          5));
      current_statement__ = 19;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 17;
        prior_ = (prior_ +
          stan::math::normal_lpdf<false>(
            stan::math::to_vector(
              stan::model::rvalue(beta_s_raw, "beta_s_raw",
                stan::model::index_uni(s))), 0, 5));
      }
      current_statement__ = 24;
      for (int c = 1; c <= C; ++c) {
        current_statement__ = 22;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 20;
          prior_ = (prior_ +
            stan::math::dirichlet_lpdf<false>(
              stan::model::rvalue(B, "B", stan::model::index_uni(c),
                stan::model::index_uni(s)), stan::math::rep_vector(2, M)));
        }
      }
      {
        current_statement__ = 25;
        stan::math::validate_non_negative_index("ll", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> ll =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 27;
        stan::math::validate_non_negative_index("log_Pi", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,1> log_Pi =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 29;
        stan::math::validate_non_negative_index("log_B", "C", C);
        current_statement__ = 30;
        stan::math::validate_non_negative_index("log_B", "S", S);
        current_statement__ = 31;
        stan::math::validate_non_negative_index("log_B", "M", M);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> log_B =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(C,
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, M,
              DUMMY_VAR__));
        current_statement__ = 33;
        stan::math::validate_non_negative_index("log_py", "S", S);
        current_statement__ = 34;
        stan::math::validate_non_negative_index("log_py", "T", T);
        Eigen::Matrix<local_scalar_t__,-1,-1> log_py =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, T, DUMMY_VAR__);
        current_statement__ = 36;
        stan::math::validate_non_negative_index("log_A", "T", T);
        current_statement__ = 37;
        stan::math::validate_non_negative_index("log_A", "S", S);
        current_statement__ = 38;
        stan::math::validate_non_negative_index("log_A", "S", S);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> log_A =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(T,
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, S,
              DUMMY_VAR__));
        current_statement__ = 44;
        for (int c = 1; c <= C; ++c) {
          current_statement__ = 42;
          for (int s = 1; s <= S; ++s) {
            current_statement__ = 40;
            stan::model::assign(log_B,
              stan::math::log(
                stan::math::transpose(
                  stan::model::rvalue(B, "B", stan::model::index_uni(c),
                    stan::model::index_uni(s)))), "assigning variable log_B",
              stan::model::index_uni(c), stan::model::index_uni(s),
              stan::model::index_omni());
          }
        }
        current_statement__ = 45;
        stan::math::validate_non_negative_index("zeros", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,1> zeros =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 46;
        stan::model::assign(zeros, stan::math::rep_vector(0, S),
          "assigning variable zeros");
        current_statement__ = 61;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 47;
          stan::model::assign(log_Pi,
            stan::math::log_softmax(
              stan::math::add(alpha_i,
                stan::math::multiply(beta_i,
                  stan::model::rvalue(X_i, "X_i", stan::model::index_uni(i))))),
            "assigning variable log_Pi");
          current_statement__ = 58;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 50;
            for (int s = 1; s <= S; ++s) {
              current_statement__ = 48;
              stan::model::assign(log_A,
                stan::math::transpose(
                  stan::math::log_softmax(
                    stan::math::multiply(
                      stan::model::rvalue(beta_s, "beta_s",
                        stan::model::index_uni(s)),
                      stan::model::rvalue(X_s, "X_s",
                        stan::model::index_uni(t), stan::model::index_uni(i))))),
                "assigning variable log_A", stan::model::index_uni(t),
                stan::model::index_uni(s), stan::model::index_omni());
            }
            current_statement__ = 51;
            stan::model::assign(log_py, zeros, "assigning variable log_py",
              stan::model::index_omni(), stan::model::index_uni(t));
            current_statement__ = 56;
            for (int c = 1; c <= C; ++c) {
              current_statement__ = 54;
              if (stan::math::logical_gt(
                    stan::model::rvalue(obs, "obs",
                      stan::model::index_uni(c), stan::model::index_uni(t),
                      stan::model::index_uni(i)), 0)) {
                current_statement__ = 52;
                stan::model::assign(log_py,
                  stan::math::add(
                    stan::model::deep_copy(
                      stan::model::rvalue(log_py, "log_py",
                        stan::model::index_omni(), stan::model::index_uni(t))),
                    stan::model::rvalue(log_B, "log_B",
                      stan::model::index_uni(c), stan::model::index_omni(),
                      stan::model::index_uni(
                        stan::model::rvalue(obs, "obs",
                          stan::model::index_uni(c),
                          stan::model::index_uni(t),
                          stan::model::index_uni(i))))),
                  "assigning variable log_py", stan::model::index_omni(),
                  stan::model::index_uni(t));
              }
            }
          }
          current_statement__ = 59;
          stan::model::assign(ll, loglik(log_Pi, log_A, log_py, pstream__),
            "assigning variable ll", stan::model::index_uni(i));
        }
        current_statement__ = 62;
        log_lik_ = stan::math::sum(ll);
      }
      {
        current_statement__ = 64;
        lp_accum__.add(prior_);
        current_statement__ = 65;
        lp_accum__.add(log_lik_);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_multichannel_nhmm_vvc_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> alpha_i_raw =
        Eigen::Matrix<double,-1,1>::Constant(alpha_i_raw_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      alpha_i_raw = in__.template read_constrain_positive_ordered<
                      Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
                      alpha_i_raw_1dim__);
      Eigen::Matrix<double,-1,-1> beta_i_raw =
        Eigen::Matrix<double,-1,-1>::Constant(beta_i_raw_1dim__, K_i,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta_i_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
                     K_i);
      std::vector<Eigen::Matrix<double,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<double,-1,-1>>(S,
          Eigen::Matrix<double,-1,-1>::Constant(beta_s_raw_2dim__, K_s,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 3;
      beta_s_raw = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(S,
                     beta_s_raw_2dim__, K_s);
      std::vector<std::vector<Eigen::Matrix<double,-1,1>>> B =
        std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(C,
          std::vector<Eigen::Matrix<double,-1,1>>(S,
            Eigen::Matrix<double,-1,1>::Constant(M,
              std::numeric_limits<double>::quiet_NaN())));
      current_statement__ = 4;
      B = in__.template read_constrain_simplex<
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>,
            jacobian__>(lp__, C, S, M);
      double log_lik_ = std::numeric_limits<double>::quiet_NaN();
      double prior_ = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,1> alpha_i =
        Eigen::Matrix<double,-1,1>::Constant(S,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> beta_i =
        Eigen::Matrix<double,-1,-1>::Constant(S, K_i,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<Eigen::Matrix<double,-1,-1>> beta_s =
        std::vector<Eigen::Matrix<double,-1,-1>>(S,
          Eigen::Matrix<double,-1,-1>::Constant(S, K_s,
            std::numeric_limits<double>::quiet_NaN()));
      out__.write(alpha_i_raw);
      out__.write(beta_i_raw);
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            out__.write(stan::model::rvalue(beta_s_raw, "beta_s_raw",
                          stan::model::index_uni(sym3__),
                          stan::model::index_uni(sym2__),
                          stan::model::index_uni(sym1__)));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= C; ++sym3__) {
            out__.write(B[(sym3__ - 1)][(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
      }
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 6;
      prior_ = 0.0;
      current_statement__ = 7;
      stan::model::assign(alpha_i,
        stan::math::reverse(stan::math::append_row(0, alpha_i_raw)),
        "assigning variable alpha_i");
      current_statement__ = 8;
      stan::model::assign(beta_i,
        stan::math::append_row(stan::math::rep_row_vector(0, K_i), beta_i_raw),
        "assigning variable beta_i");
      current_statement__ = 14;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 12;
        stan::model::assign(beta_s,
          stan::math::append_row(stan::math::rep_row_vector(0, K_s),
            stan::model::rvalue(beta_s_raw, "beta_s_raw",
              stan::model::index_uni(s))), "assigning variable beta_s",
          stan::model::index_uni(s));
      }
      current_statement__ = 15;
      prior_ = (prior_ + stan::math::normal_lpdf<false>(alpha_i_raw, 0, 5));
      current_statement__ = 16;
      prior_ = (prior_ +
        stan::math::normal_lpdf<false>(stan::math::to_vector(beta_i_raw), 0,
          5));
      current_statement__ = 19;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 17;
        prior_ = (prior_ +
          stan::math::normal_lpdf<false>(
            stan::math::to_vector(
              stan::model::rvalue(beta_s_raw, "beta_s_raw",
                stan::model::index_uni(s))), 0, 5));
      }
      current_statement__ = 24;
      for (int c = 1; c <= C; ++c) {
        current_statement__ = 22;
        for (int s = 1; s <= S; ++s) {
          current_statement__ = 20;
          prior_ = (prior_ +
            stan::math::dirichlet_lpdf<false>(
              stan::model::rvalue(B, "B", stan::model::index_uni(c),
                stan::model::index_uni(s)), stan::math::rep_vector(2, M)));
        }
      }
      {
        current_statement__ = 25;
        stan::math::validate_non_negative_index("ll", "N", N);
        Eigen::Matrix<double,-1,1> ll =
          Eigen::Matrix<double,-1,1>::Constant(N,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 27;
        stan::math::validate_non_negative_index("log_Pi", "S", S);
        Eigen::Matrix<double,-1,1> log_Pi =
          Eigen::Matrix<double,-1,1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 29;
        stan::math::validate_non_negative_index("log_B", "C", C);
        current_statement__ = 30;
        stan::math::validate_non_negative_index("log_B", "S", S);
        current_statement__ = 31;
        stan::math::validate_non_negative_index("log_B", "M", M);
        std::vector<Eigen::Matrix<double,-1,-1>> log_B =
          std::vector<Eigen::Matrix<double,-1,-1>>(C,
            Eigen::Matrix<double,-1,-1>::Constant(S, M,
              std::numeric_limits<double>::quiet_NaN()));
        current_statement__ = 33;
        stan::math::validate_non_negative_index("log_py", "S", S);
        current_statement__ = 34;
        stan::math::validate_non_negative_index("log_py", "T", T);
        Eigen::Matrix<double,-1,-1> log_py =
          Eigen::Matrix<double,-1,-1>::Constant(S, T,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 36;
        stan::math::validate_non_negative_index("log_A", "T", T);
        current_statement__ = 37;
        stan::math::validate_non_negative_index("log_A", "S", S);
        current_statement__ = 38;
        stan::math::validate_non_negative_index("log_A", "S", S);
        std::vector<Eigen::Matrix<double,-1,-1>> log_A =
          std::vector<Eigen::Matrix<double,-1,-1>>(T,
            Eigen::Matrix<double,-1,-1>::Constant(S, S,
              std::numeric_limits<double>::quiet_NaN()));
        current_statement__ = 44;
        for (int c = 1; c <= C; ++c) {
          current_statement__ = 42;
          for (int s = 1; s <= S; ++s) {
            current_statement__ = 40;
            stan::model::assign(log_B,
              stan::math::log(
                stan::math::transpose(
                  stan::model::rvalue(B, "B", stan::model::index_uni(c),
                    stan::model::index_uni(s)))), "assigning variable log_B",
              stan::model::index_uni(c), stan::model::index_uni(s),
              stan::model::index_omni());
          }
        }
        current_statement__ = 45;
        stan::math::validate_non_negative_index("zeros", "S", S);
        Eigen::Matrix<double,-1,1> zeros =
          Eigen::Matrix<double,-1,1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 46;
        stan::model::assign(zeros, stan::math::rep_vector(0, S),
          "assigning variable zeros");
        current_statement__ = 61;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 47;
          stan::model::assign(log_Pi,
            stan::math::log_softmax(
              stan::math::add(alpha_i,
                stan::math::multiply(beta_i,
                  stan::model::rvalue(X_i, "X_i", stan::model::index_uni(i))))),
            "assigning variable log_Pi");
          current_statement__ = 58;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 50;
            for (int s = 1; s <= S; ++s) {
              current_statement__ = 48;
              stan::model::assign(log_A,
                stan::math::transpose(
                  stan::math::log_softmax(
                    stan::math::multiply(
                      stan::model::rvalue(beta_s, "beta_s",
                        stan::model::index_uni(s)),
                      stan::model::rvalue(X_s, "X_s",
                        stan::model::index_uni(t), stan::model::index_uni(i))))),
                "assigning variable log_A", stan::model::index_uni(t),
                stan::model::index_uni(s), stan::model::index_omni());
            }
            current_statement__ = 51;
            stan::model::assign(log_py, zeros, "assigning variable log_py",
              stan::model::index_omni(), stan::model::index_uni(t));
            current_statement__ = 56;
            for (int c = 1; c <= C; ++c) {
              current_statement__ = 54;
              if (stan::math::logical_gt(
                    stan::model::rvalue(obs, "obs",
                      stan::model::index_uni(c), stan::model::index_uni(t),
                      stan::model::index_uni(i)), 0)) {
                current_statement__ = 52;
                stan::model::assign(log_py,
                  stan::math::add(
                    stan::model::deep_copy(
                      stan::model::rvalue(log_py, "log_py",
                        stan::model::index_omni(), stan::model::index_uni(t))),
                    stan::model::rvalue(log_B, "log_B",
                      stan::model::index_uni(c), stan::model::index_omni(),
                      stan::model::index_uni(
                        stan::model::rvalue(obs, "obs",
                          stan::model::index_uni(c),
                          stan::model::index_uni(t),
                          stan::model::index_uni(i))))),
                  "assigning variable log_py", stan::model::index_omni(),
                  stan::model::index_uni(t));
              }
            }
          }
          current_statement__ = 59;
          stan::model::assign(ll, loglik(log_Pi, log_A, log_py, pstream__),
            "assigning variable ll", stan::model::index_uni(i));
        }
        current_statement__ = 62;
        log_lik_ = stan::math::sum(ll);
      }
      if (emit_transformed_parameters__) {
        out__.write(log_lik_);
        out__.write(prior_);
        out__.write(alpha_i);
        out__.write(beta_i);
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              out__.write(stan::model::rvalue(beta_s, "beta_s",
                            stan::model::index_uni(sym3__),
                            stan::model::index_uni(sym2__),
                            stan::model::index_uni(sym1__)));
            }
          }
        }
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double prior = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 10;
      prior = prior_;
      double log_lik = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 11;
      log_lik = log_lik_;
      out__.write(prior);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(alpha_i_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(alpha_i_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(alpha_i_raw_1dim__),
        "assigning variable alpha_i_raw");
      out__.write_free_positive_ordered(alpha_i_raw);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta_i_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
          K_i), "assigning variable beta_i_raw");
      out__.write(beta_i_raw);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        current_statement__ = 3;
        for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
          current_statement__ = 3;
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            current_statement__ = 3;
            stan::model::assign(beta_s_raw, in__.read<local_scalar_t__>(),
              "assigning variable beta_s_raw",
              stan::model::index_uni(sym3__), stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write(beta_s_raw);
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> B =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(C,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__)));
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 4;
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          current_statement__ = 4;
          for (int sym3__ = 1; sym3__ <= C; ++sym3__) {
            current_statement__ = 4;
            stan::model::assign(B, in__.read<local_scalar_t__>(),
              "assigning variable B", stan::model::index_uni(sym3__),
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write_free_simplex(B);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha_i_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(alpha_i_raw_1dim__)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_i_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(beta_i_raw_1dim__),
          static_cast<size_t>(K_i)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta_s_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(S),
          static_cast<size_t>(beta_s_raw_2dim__), static_cast<size_t>(K_s)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "B", "double",
        std::vector<size_t>{static_cast<size_t>(C), static_cast<size_t>(S),
          static_cast<size_t>(M)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(alpha_i_raw_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_i_raw_flat__;
        current_statement__ = 1;
        alpha_i_raw_flat__ = context__.vals_r("alpha_i_raw");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= alpha_i_raw_1dim__; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(alpha_i_raw, alpha_i_raw_flat__[(pos__ - 1)],
            "assigning variable alpha_i_raw", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_positive_ordered(alpha_i_raw);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_i_raw_flat__;
        current_statement__ = 2;
        beta_i_raw_flat__ = context__.vals_r("beta_i_raw");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
            current_statement__ = 2;
            stan::model::assign(beta_i_raw, beta_i_raw_flat__[(pos__ - 1)],
              "assigning variable beta_i_raw",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta_i_raw);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> beta_s_raw_flat__;
        current_statement__ = 3;
        beta_s_raw_flat__ = context__.vals_r("beta_s_raw");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
            current_statement__ = 3;
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              current_statement__ = 3;
              stan::model::assign(beta_s_raw, beta_s_raw_flat__[(pos__ - 1)],
                "assigning variable beta_s_raw",
                stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 3;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write(beta_s_raw);
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> B =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(C,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(S,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(M, DUMMY_VAR__)));
      {
        std::vector<local_scalar_t__> B_flat__;
        current_statement__ = 4;
        B_flat__ = context__.vals_r("B");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
            current_statement__ = 4;
            for (int sym3__ = 1; sym3__ <= C; ++sym3__) {
              current_statement__ = 4;
              stan::model::assign(B, B_flat__[(pos__ - 1)],
                "assigning variable B", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 4;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write_free_simplex(B);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha_i_raw", "beta_i_raw",
                "beta_s_raw", "B"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"log_lik_", "prior_", "alpha_i", "beta_i", "beta_s"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"prior", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    alpha_i_raw_1dim__)},
                std::vector<size_t>{static_cast<size_t>(beta_i_raw_1dim__),
                  static_cast<size_t>(K_i)},
                std::vector<size_t>{static_cast<size_t>(S),
                  static_cast<size_t>(beta_s_raw_2dim__),
                  static_cast<size_t>(K_s)},
                std::vector<size_t>{static_cast<size_t>(C),
                  static_cast<size_t>(S), static_cast<size_t>(M)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(S)},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(K_i)},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(S), static_cast<size_t>(K_s)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= alpha_i_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha_i_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta_i_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
          param_names__.emplace_back(std::string() + "beta_s_raw" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= C; ++sym3__) {
          param_names__.emplace_back(std::string() + "B" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik_");
      param_names__.emplace_back(std::string() + "prior_");
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        param_names__.emplace_back(std::string() + "alpha_i" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_i" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta_s" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "prior");
      param_names__.emplace_back(std::string() + "log_lik");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= alpha_i_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha_i_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta_i_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
          param_names__.emplace_back(std::string() + "beta_s_raw" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= (M - 1); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= C; ++sym3__) {
          param_names__.emplace_back(std::string() + "B" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik_");
      param_names__.emplace_back(std::string() + "prior_");
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        param_names__.emplace_back(std::string() + "alpha_i" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_i" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta_s" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "prior");
      param_names__.emplace_back(std::string() + "log_lik");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha_i_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(alpha_i_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"beta_i_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_i_raw_1dim__) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"parameters\"},{\"name\":\"beta_s_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_s_raw_2dim__) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"parameters\"},{\"name\":\"B\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(C) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "}}},\"block\":\"parameters\"},{\"name\":\"log_lik_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"alpha_i\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_i\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_s\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"prior\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha_i_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(alpha_i_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"beta_i_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_i_raw_1dim__) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"parameters\"},{\"name\":\"beta_s_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_s_raw_2dim__) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"parameters\"},{\"name\":\"B\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(C) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((M -1)) + "}}},\"block\":\"parameters\"},{\"name\":\"log_lik_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"alpha_i\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_i\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_s\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"prior\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((alpha_i_raw_1dim__ + (beta_i_raw_1dim__ *
      K_i)) + ((S * beta_s_raw_2dim__) * K_s)) + ((C * S) * M));
    const size_t num_transformed = emit_transformed_parameters * (((((1 + 1)
      + S) + (S * K_i)) + ((S * S) * K_s)));
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((alpha_i_raw_1dim__ + (beta_i_raw_1dim__ *
      K_i)) + ((S * beta_s_raw_2dim__) * K_s)) + ((C * S) * M));
    const size_t num_transformed = emit_transformed_parameters * (((((1 + 1)
      + S) + (S * K_i)) + ((S * S) * K_s)));
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_multichannel_nhmm_vvc_namespace::model_multichannel_nhmm_vvc;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_multichannel_nhmm_vvc_namespace::profiles__;
}
#endif
#endif
