// Generated by rstantools.  Do not edit by hand.

/*
    seqHMM is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    seqHMM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with seqHMM.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_multichannel_nhmm_vvv_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 172> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 79, column 0 to column 36)",
  " (in 'string', line 80, column 0 to column 30)",
  " (in 'string', line 82, column 0 to column 39)",
  " (in 'string', line 84, column 0 to column 45)",
  " (in 'string', line 87, column 2 to column 16)",
  " (in 'string', line 88, column 2 to column 20)",
  " (in 'string', line 89, column 0 to column 56)",
  " (in 'string', line 90, column 0 to column 71)",
  " (in 'string', line 91, column 0 to column 31)",
  " (in 'string', line 95, column 0 to column 34)",
  " (in 'string', line 153, column 2 to column 22)",
  " (in 'string', line 154, column 2 to column 26)",
  " (in 'string', line 93, column 2 to column 64)",
  " (in 'string', line 92, column 14 to line 94, column 1)",
  " (in 'string', line 92, column 0 to line 94, column 1)",
  " (in 'string', line 97, column 8 to column 11)",
  " (in 'string', line 97, column 2 to column 60)",
  " (in 'string', line 98, column 13 to column 16)",
  " (in 'string', line 98, column 2 to column 49)",
  " (in 'string', line 101, column 6 to column 32)",
  " (in 'string', line 103, column 14 to column 17)",
  " (in 'string', line 103, column 8 to column 113)",
  " (in 'string', line 104, column 8 to column 44)",
  " (in 'string', line 102, column 21 to line 105, column 7)",
  " (in 'string', line 102, column 6 to line 105, column 7)",
  " (in 'string', line 100, column 19 to line 106, column 5)",
  " (in 'string', line 100, column 4 to line 106, column 5)",
  " (in 'string', line 99, column 17 to line 107, column 3)",
  " (in 'string', line 99, column 2 to line 107, column 3)",
  " (in 'string', line 96, column 0 to line 108, column 1)",
  " (in 'string', line 110, column 0 to column 42)",
  " (in 'string', line 111, column 0 to column 52)",
  " (in 'string', line 114, column 2 to column 57)",
  " (in 'string', line 113, column 14 to line 115, column 1)",
  " (in 'string', line 113, column 0 to line 115, column 1)",
  " (in 'string', line 117, column 0 to column 41)",
  " (in 'string', line 119, column 11 to column 12)",
  " (in 'string', line 119, column 4 to column 17)",
  " (in 'string', line 120, column 11 to column 12)",
  " (in 'string', line 120, column 4 to column 21)",
  " (in 'string', line 121, column 10 to column 11)",
  " (in 'string', line 121, column 20 to column 21)",
  " (in 'string', line 121, column 23 to column 24)",
  " (in 'string', line 121, column 4 to column 32)",
  " (in 'string', line 122, column 11 to column 12)",
  " (in 'string', line 122, column 14 to column 15)",
  " (in 'string', line 122, column 4 to column 24)",
  " (in 'string', line 123, column 10 to column 11)",
  " (in 'string', line 123, column 20 to column 21)",
  " (in 'string', line 123, column 23 to column 24)",
  " (in 'string', line 123, column 4 to column 32)",
  " (in 'string', line 124, column 11 to column 12)",
  " (in 'string', line 124, column 4 to column 39)",
  " (in 'string', line 126, column 0 to column 48)",
  " (in 'string', line 129, column 2 to column 54)",
  " (in 'string', line 128, column 14 to line 130, column 1)",
  " (in 'string', line 128, column 0 to line 130, column 1)",
  " (in 'string', line 133, column 4 to column 59)",
  " (in 'string', line 132, column 16 to line 134, column 3)",
  " (in 'string', line 132, column 2 to line 134, column 3)",
  " (in 'string', line 131, column 14 to line 135, column 1)",
  " (in 'string', line 131, column 0 to line 135, column 1)",
  " (in 'string', line 136, column 8 to column 28)",
  " (in 'string', line 139, column 12 to column 52)",
  " (in 'string', line 138, column 31 to line 140, column 11)",
  " (in 'string', line 138, column 10 to line 140, column 11)",
  " (in 'string', line 137, column 22 to line 141, column 9)",
  " (in 'string', line 137, column 8 to line 141, column 9)",
  " (in 'string', line 127, column 20 to line 142, column 7)",
  " (in 'string', line 127, column 6 to line 142, column 7)",
  " (in 'string', line 143, column 6 to column 44)",
  " (in 'string', line 125, column 18 to line 144, column 5)",
  " (in 'string', line 125, column 4 to line 144, column 5)",
  " (in 'string', line 145, column 4 to column 23)",
  " (in 'string', line 118, column 2 to line 146, column 3)",
  " (in 'string', line 149, column 2 to column 19)",
  " (in 'string', line 150, column 2 to column 21)",
  " (in 'string', line 64, column 0 to column 15)",
  " (in 'string', line 65, column 0 to column 15)",
  " (in 'string', line 66, column 0 to column 15)",
  " (in 'string', line 67, column 0 to column 15)",
  " (in 'string', line 68, column 0 to column 15)",
  " (in 'string', line 69, column 6 to column 7)",
  " (in 'string', line 69, column 9 to column 10)",
  " (in 'string', line 69, column 12 to column 13)",
  " (in 'string', line 69, column 0 to column 40)",
  " (in 'string', line 70, column 0 to column 17)",
  " (in 'string', line 71, column 6 to column 7)",
  " (in 'string', line 71, column 16 to column 19)",
  " (in 'string', line 71, column 0 to column 25)",
  " (in 'string', line 72, column 0 to column 17)",
  " (in 'string', line 73, column 6 to column 7)",
  " (in 'string', line 73, column 9 to column 10)",
  " (in 'string', line 73, column 19 to column 22)",
  " (in 'string', line 73, column 0 to column 28)",
  " (in 'string', line 74, column 0 to column 17)",
  " (in 'string', line 75, column 6 to column 7)",
  " (in 'string', line 75, column 9 to column 10)",
  " (in 'string', line 75, column 19 to column 22)",
  " (in 'string', line 75, column 0 to column 28)",
  " (in 'string', line 79, column 17 to column 22)",
  " (in 'string', line 80, column 7 to column 12)",
  " (in 'string', line 80, column 14 to column 17)",
  " (in 'string', line 82, column 6 to column 7)",
  " (in 'string', line 82, column 16 to column 21)",
  " (in 'string', line 82, column 23 to column 26)",
  " (in 'string', line 84, column 11 to column 32)",
  " (in 'string', line 89, column 7 to column 8)",
  " (in 'string', line 90, column 7 to column 8)",
  " (in 'string', line 90, column 10 to column 13)",
  " (in 'string', line 91, column 6 to column 7)",
  " (in 'string', line 91, column 16 to column 17)",
  " (in 'string', line 91, column 19 to column 22)",
  " (in 'string', line 95, column 6 to column 7)",
  " (in 'string', line 95, column 9 to column 10)",
  " (in 'string', line 95, column 19 to column 20)",
  " (in 'string', line 95, column 22 to column 25)",
  " (in 'string', line 6, column 2 to column 23)",
  " (in 'string', line 7, column 2 to column 23)",
  " (in 'string', line 8, column 9 to column 10)",
  " (in 'string', line 8, column 2 to column 22)",
  " (in 'string', line 9, column 9 to column 10)",
  " (in 'string', line 9, column 2 to column 26)",
  " (in 'string', line 10, column 2 to column 35)",
  " (in 'string', line 13, column 6 to column 79)",
  " (in 'string', line 12, column 19 to line 14, column 5)",
  " (in 'string', line 12, column 4 to line 14, column 5)",
  " (in 'string', line 15, column 4 to column 30)",
  " (in 'string', line 11, column 17 to line 16, column 3)",
  " (in 'string', line 11, column 2 to line 16, column 3)",
  " (in 'string', line 17, column 2 to column 32)",
  " (in 'string', line 5, column 64 to line 18, column 1)",
  " (in 'string', line 20, column 2 to column 23)",
  " (in 'string', line 21, column 2 to column 23)",
  " (in 'string', line 22, column 9 to column 10)",
  " (in 'string', line 22, column 2 to column 22)",
  " (in 'string', line 23, column 9 to column 10)",
  " (in 'string', line 23, column 2 to column 26)",
  " (in 'string', line 24, column 2 to column 35)",
  " (in 'string', line 27, column 6 to column 76)",
  " (in 'string', line 26, column 19 to line 28, column 5)",
  " (in 'string', line 26, column 4 to line 28, column 5)",
  " (in 'string', line 29, column 4 to column 30)",
  " (in 'string', line 25, column 17 to line 30, column 3)",
  " (in 'string', line 25, column 2 to line 30, column 3)",
  " (in 'string', line 31, column 2 to column 32)",
  " (in 'string', line 19, column 56 to line 32, column 1)",
  " (in 'string', line 39, column 2 to column 23)",
  " (in 'string', line 40, column 8 to column 14)",
  " (in 'string', line 40, column 2 to column 22)",
  " (in 'string', line 42, column 4 to column 23)",
  " (in 'string', line 41, column 21 to line 43, column 3)",
  " (in 'string', line 41, column 2 to line 43, column 3)",
  " (in 'string', line 44, column 2 to column 11)",
  " (in 'string', line 38, column 46 to line 45, column 1)",
  " (in 'string', line 47, column 2 to column 23)",
  " (in 'string', line 48, column 8 to column 14)",
  " (in 'string', line 48, column 2 to column 22)",
  " (in 'string', line 50, column 4 to column 20)",
  " (in 'string', line 49, column 21 to line 51, column 3)",
  " (in 'string', line 49, column 2 to line 51, column 3)",
  " (in 'string', line 52, column 2 to column 11)",
  " (in 'string', line 46, column 38 to line 53, column 1)",
  " (in 'string', line 55, column 2 to column 23)",
  " (in 'string', line 56, column 8 to column 14)",
  " (in 'string', line 56, column 2 to column 22)",
  " (in 'string', line 58, column 4 to column 20)",
  " (in 'string', line 57, column 21 to line 59, column 3)",
  " (in 'string', line 57, column 2 to line 59, column 3)",
  " (in 'string', line 60, column 2 to column 11)",
  " (in 'string', line 54, column 38 to line 61, column 1)"};
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, T1__, stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__,
       const std::vector<Eigen::Matrix<T1__,-1,-1>>& log_A, const T2__&
       log_py_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
  stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__, const T1__& log_A_arg__, const T2__&
       log_py_arg__, std::ostream* pstream__);
std::vector<int>
add(const std::vector<int>& x, const std::vector<int>& y, std::ostream*
    pstream__);
std::vector<int>
add(const int& x, const std::vector<int>& y, std::ostream* pstream__);
std::vector<int>
add(const std::vector<int>& x, const int& y, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, T1__, stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__,
       const std::vector<Eigen::Matrix<T1__,-1,-1>>& log_A, const T2__&
       log_py_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             T1__, stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& log_Pi = stan::math::to_ref(log_Pi_arg__);
  const auto& log_py = stan::math::to_ref(log_py_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int S = std::numeric_limits<int>::min();
    current_statement__ = 118;
    S = stan::math::rows(log_py);
    int T = std::numeric_limits<int>::min();
    current_statement__ = 119;
    T = stan::math::cols(log_py);
    current_statement__ = 120;
    stan::math::validate_non_negative_index("log_alpha", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 122;
    stan::math::validate_non_negative_index("log_alpha_new", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 124;
    stan::model::assign(log_alpha,
      stan::math::add(log_Pi,
        stan::model::rvalue(log_py, "log_py", stan::model::index_omni(),
          stan::model::index_uni(1))), "assigning variable log_alpha");
    current_statement__ = 130;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 127;
      for (int k = 1; k <= S; ++k) {
        current_statement__ = 125;
        stan::model::assign(log_alpha_new,
          stan::math::log_sum_exp(
            stan::math::add(
              stan::math::add(log_alpha,
                stan::model::rvalue(log_A, "log_A",
                  stan::model::index_uni(t), stan::model::index_omni(),
                  stan::model::index_uni(k))),
              stan::model::rvalue(log_py, "log_py",
                stan::model::index_uni(k), stan::model::index_uni(t)))),
          "assigning variable log_alpha_new", stan::model::index_uni(k));
      }
      current_statement__ = 128;
      stan::model::assign(log_alpha, log_alpha_new,
        "assigning variable log_alpha");
    }
    current_statement__ = 131;
    return stan::math::log_sum_exp(log_alpha);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T0__>, stan::base_type_t<T1__>,
  stan::base_type_t<T2__>>
loglik(const T0__& log_Pi_arg__, const T1__& log_A_arg__, const T2__&
       log_py_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>,
                             stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& log_Pi = stan::math::to_ref(log_Pi_arg__);
  const auto& log_A = stan::math::to_ref(log_A_arg__);
  const auto& log_py = stan::math::to_ref(log_py_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int S = std::numeric_limits<int>::min();
    current_statement__ = 133;
    S = stan::math::rows(log_py);
    int T = std::numeric_limits<int>::min();
    current_statement__ = 134;
    T = stan::math::cols(log_py);
    current_statement__ = 135;
    stan::math::validate_non_negative_index("log_alpha", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 137;
    stan::math::validate_non_negative_index("log_alpha_new", "S", S);
    Eigen::Matrix<local_scalar_t__,-1,1> log_alpha_new =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
    current_statement__ = 139;
    stan::model::assign(log_alpha,
      stan::math::add(log_Pi,
        stan::model::rvalue(log_py, "log_py", stan::model::index_omni(),
          stan::model::index_uni(1))), "assigning variable log_alpha");
    current_statement__ = 145;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 142;
      for (int k = 1; k <= S; ++k) {
        current_statement__ = 140;
        stan::model::assign(log_alpha_new,
          stan::math::log_sum_exp(
            stan::math::add(
              stan::math::add(log_alpha,
                stan::model::rvalue(log_A, "log_A",
                  stan::model::index_omni(), stan::model::index_uni(k))),
              stan::model::rvalue(log_py, "log_py",
                stan::model::index_uni(k), stan::model::index_uni(t)))),
          "assigning variable log_alpha_new", stan::model::index_uni(k));
      }
      current_statement__ = 143;
      stan::model::assign(log_alpha, log_alpha_new,
        "assigning variable log_alpha");
    }
    current_statement__ = 146;
    return stan::math::log_sum_exp(log_alpha);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
std::vector<int>
add(const std::vector<int>& x, const std::vector<int>& y, std::ostream*
    pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int x_size = std::numeric_limits<int>::min();
    current_statement__ = 148;
    x_size = stan::math::size(x);
    current_statement__ = 149;
    stan::math::validate_non_negative_index("z", "x_size", x_size);
    std::vector<int> z =
      std::vector<int>(x_size, std::numeric_limits<int>::min());
    current_statement__ = 153;
    for (int i = 1; i <= x_size; ++i) {
      current_statement__ = 151;
      stan::model::assign(z,
        (stan::model::rvalue(x, "x", stan::model::index_uni(i)) +
        stan::model::rvalue(y, "y", stan::model::index_uni(i))),
        "assigning variable z", stan::model::index_uni(i));
    }
    current_statement__ = 154;
    return z;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
std::vector<int>
add(const int& x, const std::vector<int>& y, std::ostream* pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int y_size = std::numeric_limits<int>::min();
    current_statement__ = 156;
    y_size = stan::math::size(y);
    current_statement__ = 157;
    stan::math::validate_non_negative_index("z", "y_size", y_size);
    std::vector<int> z =
      std::vector<int>(y_size, std::numeric_limits<int>::min());
    current_statement__ = 161;
    for (int i = 1; i <= y_size; ++i) {
      current_statement__ = 159;
      stan::model::assign(z, (x +
        stan::model::rvalue(y, "y", stan::model::index_uni(i))),
        "assigning variable z", stan::model::index_uni(i));
    }
    current_statement__ = 162;
    return z;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
std::vector<int>
add(const std::vector<int>& x, const int& y, std::ostream* pstream__) {
  using local_scalar_t__ = double;
  int current_statement__ = 0;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int x_size = std::numeric_limits<int>::min();
    current_statement__ = 164;
    x_size = stan::math::size(x);
    current_statement__ = 165;
    stan::math::validate_non_negative_index("z", "x_size", x_size);
    std::vector<int> z =
      std::vector<int>(x_size, std::numeric_limits<int>::min());
    current_statement__ = 169;
    for (int i = 1; i <= x_size; ++i) {
      current_statement__ = 167;
      stan::model::assign(z,
        (stan::model::rvalue(x, "x", stan::model::index_uni(i)) + y),
        "assigning variable z", stan::model::index_uni(i));
    }
    current_statement__ = 170;
    return z;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_multichannel_nhmm_vvv final : public model_base_crtp<model_multichannel_nhmm_vvv> {
private:
  int N;
  int T;
  int M;
  int S;
  int C;
  std::vector<std::vector<std::vector<int>>> obs;
  int K_i;
  std::vector<Eigen::Matrix<double,-1,1>> X_i;
  int K_s;
  std::vector<std::vector<Eigen::Matrix<double,-1,1>>> X_s;
  int K_o;
  std::vector<std::vector<Eigen::Matrix<double,-1,1>>> X_o;
  int alpha_i_raw_1dim__;
  int beta_i_raw_1dim__;
  int beta_s_raw_2dim__;
  int beta_o_raw_1dim__;
public:
  ~model_multichannel_nhmm_vvv() {}
  model_multichannel_nhmm_vvv(stan::io::var_context& context__, unsigned int
                              random_seed__ = 0, std::ostream*
                              pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_multichannel_nhmm_vvv_namespace::model_multichannel_nhmm_vvv";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 78;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 78;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 78;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 79;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 79;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 79;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 80;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 80;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 80;
      stan::math::check_greater_or_equal(function__, "M", M, 2);
      current_statement__ = 81;
      context__.validate_dims("data initialization", "S", "int",
        std::vector<size_t>{});
      S = std::numeric_limits<int>::min();
      current_statement__ = 81;
      S = context__.vals_i("S")[(1 - 1)];
      current_statement__ = 81;
      stan::math::check_greater_or_equal(function__, "S", S, 1);
      current_statement__ = 82;
      context__.validate_dims("data initialization", "C", "int",
        std::vector<size_t>{});
      C = std::numeric_limits<int>::min();
      current_statement__ = 82;
      C = context__.vals_i("C")[(1 - 1)];
      current_statement__ = 82;
      stan::math::check_greater_or_equal(function__, "C", C, 2);
      current_statement__ = 83;
      stan::math::validate_non_negative_index("obs", "C", C);
      current_statement__ = 84;
      stan::math::validate_non_negative_index("obs", "T", T);
      current_statement__ = 85;
      stan::math::validate_non_negative_index("obs", "N", N);
      current_statement__ = 86;
      context__.validate_dims("data initialization", "obs", "int",
        std::vector<size_t>{static_cast<size_t>(C), static_cast<size_t>(T),
          static_cast<size_t>(N)});
      obs = std::vector<std::vector<std::vector<int>>>(C,
              std::vector<std::vector<int>>(T,
                std::vector<int>(N, std::numeric_limits<int>::min())));
      {
        std::vector<int> obs_flat__;
        current_statement__ = 86;
        obs_flat__ = context__.vals_i("obs");
        current_statement__ = 86;
        pos__ = 1;
        current_statement__ = 86;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 86;
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            current_statement__ = 86;
            for (int sym3__ = 1; sym3__ <= C; ++sym3__) {
              current_statement__ = 86;
              stan::model::assign(obs, obs_flat__[(pos__ - 1)],
                "assigning variable obs", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 86;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 86;
      stan::math::check_greater_or_equal(function__, "obs", obs, 0);
      current_statement__ = 86;
      stan::math::check_less_or_equal(function__, "obs", obs, M);
      current_statement__ = 87;
      context__.validate_dims("data initialization", "K_i", "int",
        std::vector<size_t>{});
      K_i = std::numeric_limits<int>::min();
      current_statement__ = 87;
      K_i = context__.vals_i("K_i")[(1 - 1)];
      current_statement__ = 87;
      stan::math::check_greater_or_equal(function__, "K_i", K_i, 1);
      current_statement__ = 88;
      stan::math::validate_non_negative_index("X_i", "N", N);
      current_statement__ = 89;
      stan::math::validate_non_negative_index("X_i", "K_i", K_i);
      current_statement__ = 90;
      context__.validate_dims("data initialization", "X_i", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K_i)});
      X_i = std::vector<Eigen::Matrix<double,-1,1>>(N,
              Eigen::Matrix<double,-1,1>::Constant(K_i,
                std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> X_i_flat__;
        current_statement__ = 90;
        X_i_flat__ = context__.vals_r("X_i");
        current_statement__ = 90;
        pos__ = 1;
        current_statement__ = 90;
        for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
          current_statement__ = 90;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 90;
            stan::model::assign(X_i, X_i_flat__[(pos__ - 1)],
              "assigning variable X_i", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 90;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 91;
      context__.validate_dims("data initialization", "K_s", "int",
        std::vector<size_t>{});
      K_s = std::numeric_limits<int>::min();
      current_statement__ = 91;
      K_s = context__.vals_i("K_s")[(1 - 1)];
      current_statement__ = 91;
      stan::math::check_greater_or_equal(function__, "K_s", K_s, 1);
      current_statement__ = 92;
      stan::math::validate_non_negative_index("X_s", "T", T);
      current_statement__ = 93;
      stan::math::validate_non_negative_index("X_s", "N", N);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("X_s", "K_s", K_s);
      current_statement__ = 95;
      context__.validate_dims("data initialization", "X_s", "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(N),
          static_cast<size_t>(K_s)});
      X_s = std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(T,
              std::vector<Eigen::Matrix<double,-1,1>>(N,
                Eigen::Matrix<double,-1,1>::Constant(K_s,
                  std::numeric_limits<double>::quiet_NaN())));
      {
        std::vector<local_scalar_t__> X_s_flat__;
        current_statement__ = 95;
        X_s_flat__ = context__.vals_r("X_s");
        current_statement__ = 95;
        pos__ = 1;
        current_statement__ = 95;
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          current_statement__ = 95;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 95;
            for (int sym3__ = 1; sym3__ <= T; ++sym3__) {
              current_statement__ = 95;
              stan::model::assign(X_s, X_s_flat__[(pos__ - 1)],
                "assigning variable X_s", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 95;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 96;
      context__.validate_dims("data initialization", "K_o", "int",
        std::vector<size_t>{});
      K_o = std::numeric_limits<int>::min();
      current_statement__ = 96;
      K_o = context__.vals_i("K_o")[(1 - 1)];
      current_statement__ = 96;
      stan::math::check_greater_or_equal(function__, "K_o", K_o, 1);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("X_o", "T", T);
      current_statement__ = 98;
      stan::math::validate_non_negative_index("X_o", "N", N);
      current_statement__ = 99;
      stan::math::validate_non_negative_index("X_o", "K_o", K_o);
      current_statement__ = 100;
      context__.validate_dims("data initialization", "X_o", "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(N),
          static_cast<size_t>(K_o)});
      X_o = std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(T,
              std::vector<Eigen::Matrix<double,-1,1>>(N,
                Eigen::Matrix<double,-1,1>::Constant(K_o,
                  std::numeric_limits<double>::quiet_NaN())));
      {
        std::vector<local_scalar_t__> X_o_flat__;
        current_statement__ = 100;
        X_o_flat__ = context__.vals_r("X_o");
        current_statement__ = 100;
        pos__ = 1;
        current_statement__ = 100;
        for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
          current_statement__ = 100;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 100;
            for (int sym3__ = 1; sym3__ <= T; ++sym3__) {
              current_statement__ = 100;
              stan::model::assign(X_o, X_o_flat__[(pos__ - 1)],
                "assigning variable X_o", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 100;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 101;
      alpha_i_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 101;
      alpha_i_raw_1dim__ = (S - 1);
      current_statement__ = 101;
      stan::math::validate_non_negative_index("alpha_i_raw", "S - 1",
        alpha_i_raw_1dim__);
      current_statement__ = 102;
      beta_i_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 102;
      beta_i_raw_1dim__ = (S - 1);
      current_statement__ = 102;
      stan::math::validate_non_negative_index("beta_i_raw", "S - 1",
        beta_i_raw_1dim__);
      current_statement__ = 103;
      stan::math::validate_non_negative_index("beta_i_raw", "K_i", K_i);
      current_statement__ = 104;
      stan::math::validate_non_negative_index("beta_s_raw", "S", S);
      current_statement__ = 105;
      beta_s_raw_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 105;
      beta_s_raw_2dim__ = (S - 1);
      current_statement__ = 105;
      stan::math::validate_non_negative_index("beta_s_raw", "S - 1",
        beta_s_raw_2dim__);
      current_statement__ = 106;
      stan::math::validate_non_negative_index("beta_s_raw", "K_s", K_s);
      current_statement__ = 107;
      beta_o_raw_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 107;
      beta_o_raw_1dim__ = (((C * S) * (M - 1)) * K_o);
      current_statement__ = 107;
      stan::math::validate_non_negative_index("beta_o_raw",
        "C * S * (M - 1) * K_o", beta_o_raw_1dim__);
      current_statement__ = 108;
      stan::math::validate_non_negative_index("alpha_i", "S", S);
      current_statement__ = 109;
      stan::math::validate_non_negative_index("beta_i", "S", S);
      current_statement__ = 110;
      stan::math::validate_non_negative_index("beta_i", "K_i", K_i);
      current_statement__ = 111;
      stan::math::validate_non_negative_index("beta_s", "S", S);
      current_statement__ = 112;
      stan::math::validate_non_negative_index("beta_s", "S", S);
      current_statement__ = 113;
      stan::math::validate_non_negative_index("beta_s", "K_s", K_s);
      current_statement__ = 114;
      stan::math::validate_non_negative_index("beta_o", "C", C);
      current_statement__ = 115;
      stan::math::validate_non_negative_index("beta_o", "S", S);
      current_statement__ = 116;
      stan::math::validate_non_negative_index("beta_o", "M", M);
      current_statement__ = 117;
      stan::math::validate_non_negative_index("beta_o", "K_o", K_o);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = alpha_i_raw_1dim__ + (beta_i_raw_1dim__ * K_i) + (S *
      beta_s_raw_2dim__ * K_s) + beta_o_raw_1dim__;
  }
  inline std::string model_name() const final {
    return "model_multichannel_nhmm_vvv";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_multichannel_nhmm_vvv_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(alpha_i_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      alpha_i_raw = in__.template read_constrain_positive_ordered<
                      Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
                      alpha_i_raw_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      current_statement__ = 2;
      beta_i_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
                     K_i);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      current_statement__ = 3;
      beta_s_raw = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(S,
                     beta_s_raw_2dim__, K_s);
      Eigen::Matrix<local_scalar_t__,1,-1> beta_o_raw =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(beta_o_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 4;
      beta_o_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,1,-1>>(beta_o_raw_1dim__);
      local_scalar_t__ log_lik_ = DUMMY_VAR__;
      local_scalar_t__ prior_ = DUMMY_VAR__;
      current_statement__ = 6;
      prior_ = 0.0;
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_i =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(alpha_i,
        stan::math::reverse(stan::math::append_row(0, alpha_i_raw)),
        "assigning variable alpha_i");
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, K_i, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(beta_i,
        stan::math::append_row(stan::math::rep_row_vector(0, K_i), beta_i_raw),
        "assigning variable beta_i");
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, K_s,
            DUMMY_VAR__));
      current_statement__ = 15;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 13;
        stan::model::assign(beta_s,
          stan::math::append_row(stan::math::rep_row_vector(0, K_s),
            stan::model::rvalue(beta_s_raw, "beta_s_raw",
              stan::model::index_uni(s))), "assigning variable beta_s",
          stan::model::index_uni(s));
      }
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>
        beta_o =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(C,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(M, K_o,
              DUMMY_VAR__)));
      {
        current_statement__ = 16;
        stan::math::validate_non_negative_index("k_range", "K_o", K_o);
        std::vector<int> k_range =
          std::vector<int>(K_o, std::numeric_limits<int>::min());
        current_statement__ = 17;
        stan::model::assign(k_range,
          stan::math::linspaced_int_array(K_o, 1, K_o),
          "assigning variable k_range");
        current_statement__ = 18;
        stan::math::validate_non_negative_index("zeros", "K_o", K_o);
        Eigen::Matrix<local_scalar_t__,1,-1> zeros =
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K_o, DUMMY_VAR__);
        current_statement__ = 19;
        stan::model::assign(zeros, stan::math::rep_row_vector(0, K_o),
          "assigning variable zeros");
        current_statement__ = 29;
        for (int c = 1; c <= C; ++c) {
          current_statement__ = 27;
          for (int s = 1; s <= S; ++s) {
            current_statement__ = 20;
            stan::model::assign(beta_o, zeros, "assigning variable beta_o",
              stan::model::index_uni(c), stan::model::index_uni(s),
              stan::model::index_uni(1), stan::model::index_omni());
            current_statement__ = 25;
            for (int m = 2; m <= M; ++m) {
              current_statement__ = 21;
              stan::math::validate_non_negative_index("idx", "K_o", K_o);
              std::vector<int> idx =
                std::vector<int>(K_o, std::numeric_limits<int>::min());
              current_statement__ = 22;
              stan::model::assign(idx,
                add(k_range, ((((((c - 1) * S) * (M - 1)) * K_o) + (((s - 1)
                  * (M - 1)) * K_o)) + ((m - 2) * K_o)), pstream__),
                "assigning variable idx");
              current_statement__ = 23;
              stan::model::assign(beta_o,
                stan::model::rvalue(beta_o_raw, "beta_o_raw",
                  stan::model::index_multi(idx)),
                "assigning variable beta_o", stan::model::index_uni(c),
                stan::model::index_uni(s), stan::model::index_uni(m),
                stan::model::index_omni());
            }
          }
        }
      }
      current_statement__ = 31;
      prior_ = (prior_ + stan::math::normal_lpdf<false>(alpha_i_raw, 0, 5));
      current_statement__ = 32;
      prior_ = (prior_ +
        stan::math::normal_lpdf<false>(stan::math::to_vector(beta_i_raw), 0,
          5));
      current_statement__ = 35;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 33;
        prior_ = (prior_ +
          stan::math::normal_lpdf<false>(
            stan::math::to_vector(
              stan::model::rvalue(beta_s_raw, "beta_s_raw",
                stan::model::index_uni(s))), 0, 5));
      }
      current_statement__ = 36;
      prior_ = (prior_ + stan::math::normal_lpdf<false>(beta_o_raw, 0, 5));
      {
        current_statement__ = 37;
        stan::math::validate_non_negative_index("ll", "N", N);
        Eigen::Matrix<local_scalar_t__,-1,1> ll =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 39;
        stan::math::validate_non_negative_index("log_Pi", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,1> log_Pi =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 41;
        stan::math::validate_non_negative_index("log_B", "C", C);
        current_statement__ = 42;
        stan::math::validate_non_negative_index("log_B", "S", S);
        current_statement__ = 43;
        stan::math::validate_non_negative_index("log_B", "M", M);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> log_B =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(C,
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, M,
              DUMMY_VAR__));
        current_statement__ = 45;
        stan::math::validate_non_negative_index("log_py", "S", S);
        current_statement__ = 46;
        stan::math::validate_non_negative_index("log_py", "T", T);
        Eigen::Matrix<local_scalar_t__,-1,-1> log_py =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, T, DUMMY_VAR__);
        current_statement__ = 48;
        stan::math::validate_non_negative_index("log_A", "T", T);
        current_statement__ = 49;
        stan::math::validate_non_negative_index("log_A", "S", S);
        current_statement__ = 50;
        stan::math::validate_non_negative_index("log_A", "S", S);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> log_A =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(T,
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(S, S,
              DUMMY_VAR__));
        current_statement__ = 52;
        stan::math::validate_non_negative_index("zeros", "S", S);
        Eigen::Matrix<local_scalar_t__,-1,1> zeros =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(S, DUMMY_VAR__);
        current_statement__ = 53;
        stan::model::assign(zeros, stan::math::rep_vector(0, S),
          "assigning variable zeros");
        current_statement__ = 73;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 54;
          stan::model::assign(log_Pi,
            stan::math::log_softmax(
              stan::math::add(alpha_i,
                stan::math::multiply(beta_i,
                  stan::model::rvalue(X_i, "X_i", stan::model::index_uni(i))))),
            "assigning variable log_Pi");
          current_statement__ = 70;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 57;
            for (int s = 1; s <= S; ++s) {
              current_statement__ = 55;
              stan::model::assign(log_A,
                stan::math::transpose(
                  stan::math::log_softmax(
                    stan::math::multiply(
                      stan::model::rvalue(beta_s, "beta_s",
                        stan::model::index_uni(s)),
                      stan::model::rvalue(X_s, "X_s",
                        stan::model::index_uni(t), stan::model::index_uni(i))))),
                "assigning variable log_A", stan::model::index_uni(t),
                stan::model::index_uni(s), stan::model::index_omni());
            }
            current_statement__ = 62;
            for (int c = 1; c <= C; ++c) {
              current_statement__ = 60;
              for (int s = 1; s <= S; ++s) {
                current_statement__ = 58;
                stan::model::assign(log_B,
                  stan::math::transpose(
                    stan::math::log_softmax(
                      stan::math::multiply(
                        stan::model::rvalue(beta_o, "beta_o",
                          stan::model::index_uni(c),
                          stan::model::index_uni(s)),
                        stan::model::rvalue(X_o, "X_o",
                          stan::model::index_uni(t),
                          stan::model::index_uni(i))))),
                  "assigning variable log_B", stan::model::index_uni(c),
                  stan::model::index_uni(s), stan::model::index_omni());
              }
            }
            current_statement__ = 63;
            stan::model::assign(log_py, zeros, "assigning variable log_py",
              stan::model::index_omni(), stan::model::index_uni(t));
            current_statement__ = 68;
            for (int c = 1; c <= C; ++c) {
              current_statement__ = 66;
              if (stan::math::logical_gt(
                    stan::model::rvalue(obs, "obs",
                      stan::model::index_uni(c), stan::model::index_uni(t),
                      stan::model::index_uni(i)), 0)) {
                current_statement__ = 64;
                stan::model::assign(log_py,
                  stan::math::add(
                    stan::model::deep_copy(
                      stan::model::rvalue(log_py, "log_py",
                        stan::model::index_omni(), stan::model::index_uni(t))),
                    stan::model::rvalue(log_B, "log_B",
                      stan::model::index_uni(c), stan::model::index_omni(),
                      stan::model::index_uni(
                        stan::model::rvalue(obs, "obs",
                          stan::model::index_uni(c),
                          stan::model::index_uni(t),
                          stan::model::index_uni(i))))),
                  "assigning variable log_py", stan::model::index_omni(),
                  stan::model::index_uni(t));
              }
            }
          }
          current_statement__ = 71;
          stan::model::assign(ll, loglik(log_Pi, log_A, log_py, pstream__),
            "assigning variable ll", stan::model::index_uni(i));
        }
        current_statement__ = 74;
        log_lik_ = stan::math::sum(ll);
      }
      {
        current_statement__ = 76;
        lp_accum__.add(prior_);
        current_statement__ = 77;
        lp_accum__.add(log_lik_);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_multichannel_nhmm_vvv_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> alpha_i_raw =
        Eigen::Matrix<double,-1,1>::Constant(alpha_i_raw_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      alpha_i_raw = in__.template read_constrain_positive_ordered<
                      Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
                      alpha_i_raw_1dim__);
      Eigen::Matrix<double,-1,-1> beta_i_raw =
        Eigen::Matrix<double,-1,-1>::Constant(beta_i_raw_1dim__, K_i,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta_i_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
                     K_i);
      std::vector<Eigen::Matrix<double,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<double,-1,-1>>(S,
          Eigen::Matrix<double,-1,-1>::Constant(beta_s_raw_2dim__, K_s,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 3;
      beta_s_raw = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(S,
                     beta_s_raw_2dim__, K_s);
      Eigen::Matrix<double,1,-1> beta_o_raw =
        Eigen::Matrix<double,1,-1>::Constant(beta_o_raw_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      beta_o_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,1,-1>>(beta_o_raw_1dim__);
      double log_lik_ = std::numeric_limits<double>::quiet_NaN();
      double prior_ = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,1> alpha_i =
        Eigen::Matrix<double,-1,1>::Constant(S,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> beta_i =
        Eigen::Matrix<double,-1,-1>::Constant(S, K_i,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<Eigen::Matrix<double,-1,-1>> beta_s =
        std::vector<Eigen::Matrix<double,-1,-1>>(S,
          Eigen::Matrix<double,-1,-1>::Constant(S, K_s,
            std::numeric_limits<double>::quiet_NaN()));
      std::vector<std::vector<Eigen::Matrix<double,-1,-1>>> beta_o =
        std::vector<std::vector<Eigen::Matrix<double,-1,-1>>>(C,
          std::vector<Eigen::Matrix<double,-1,-1>>(S,
            Eigen::Matrix<double,-1,-1>::Constant(M, K_o,
              std::numeric_limits<double>::quiet_NaN())));
      out__.write(alpha_i_raw);
      out__.write(beta_i_raw);
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            out__.write(stan::model::rvalue(beta_s_raw, "beta_s_raw",
                          stan::model::index_uni(sym3__),
                          stan::model::index_uni(sym2__),
                          stan::model::index_uni(sym1__)));
          }
        }
      }
      out__.write(beta_o_raw);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 6;
      prior_ = 0.0;
      current_statement__ = 7;
      stan::model::assign(alpha_i,
        stan::math::reverse(stan::math::append_row(0, alpha_i_raw)),
        "assigning variable alpha_i");
      current_statement__ = 8;
      stan::model::assign(beta_i,
        stan::math::append_row(stan::math::rep_row_vector(0, K_i), beta_i_raw),
        "assigning variable beta_i");
      current_statement__ = 15;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 13;
        stan::model::assign(beta_s,
          stan::math::append_row(stan::math::rep_row_vector(0, K_s),
            stan::model::rvalue(beta_s_raw, "beta_s_raw",
              stan::model::index_uni(s))), "assigning variable beta_s",
          stan::model::index_uni(s));
      }
      {
        current_statement__ = 16;
        stan::math::validate_non_negative_index("k_range", "K_o", K_o);
        std::vector<int> k_range =
          std::vector<int>(K_o, std::numeric_limits<int>::min());
        current_statement__ = 17;
        stan::model::assign(k_range,
          stan::math::linspaced_int_array(K_o, 1, K_o),
          "assigning variable k_range");
        current_statement__ = 18;
        stan::math::validate_non_negative_index("zeros", "K_o", K_o);
        Eigen::Matrix<double,1,-1> zeros =
          Eigen::Matrix<double,1,-1>::Constant(K_o,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 19;
        stan::model::assign(zeros, stan::math::rep_row_vector(0, K_o),
          "assigning variable zeros");
        current_statement__ = 29;
        for (int c = 1; c <= C; ++c) {
          current_statement__ = 27;
          for (int s = 1; s <= S; ++s) {
            current_statement__ = 20;
            stan::model::assign(beta_o, zeros, "assigning variable beta_o",
              stan::model::index_uni(c), stan::model::index_uni(s),
              stan::model::index_uni(1), stan::model::index_omni());
            current_statement__ = 25;
            for (int m = 2; m <= M; ++m) {
              current_statement__ = 21;
              stan::math::validate_non_negative_index("idx", "K_o", K_o);
              std::vector<int> idx =
                std::vector<int>(K_o, std::numeric_limits<int>::min());
              current_statement__ = 22;
              stan::model::assign(idx,
                add(k_range, ((((((c - 1) * S) * (M - 1)) * K_o) + (((s - 1)
                  * (M - 1)) * K_o)) + ((m - 2) * K_o)), pstream__),
                "assigning variable idx");
              current_statement__ = 23;
              stan::model::assign(beta_o,
                stan::model::rvalue(beta_o_raw, "beta_o_raw",
                  stan::model::index_multi(idx)),
                "assigning variable beta_o", stan::model::index_uni(c),
                stan::model::index_uni(s), stan::model::index_uni(m),
                stan::model::index_omni());
            }
          }
        }
      }
      current_statement__ = 31;
      prior_ = (prior_ + stan::math::normal_lpdf<false>(alpha_i_raw, 0, 5));
      current_statement__ = 32;
      prior_ = (prior_ +
        stan::math::normal_lpdf<false>(stan::math::to_vector(beta_i_raw), 0,
          5));
      current_statement__ = 35;
      for (int s = 1; s <= S; ++s) {
        current_statement__ = 33;
        prior_ = (prior_ +
          stan::math::normal_lpdf<false>(
            stan::math::to_vector(
              stan::model::rvalue(beta_s_raw, "beta_s_raw",
                stan::model::index_uni(s))), 0, 5));
      }
      current_statement__ = 36;
      prior_ = (prior_ + stan::math::normal_lpdf<false>(beta_o_raw, 0, 5));
      {
        current_statement__ = 37;
        stan::math::validate_non_negative_index("ll", "N", N);
        Eigen::Matrix<double,-1,1> ll =
          Eigen::Matrix<double,-1,1>::Constant(N,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 39;
        stan::math::validate_non_negative_index("log_Pi", "S", S);
        Eigen::Matrix<double,-1,1> log_Pi =
          Eigen::Matrix<double,-1,1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 41;
        stan::math::validate_non_negative_index("log_B", "C", C);
        current_statement__ = 42;
        stan::math::validate_non_negative_index("log_B", "S", S);
        current_statement__ = 43;
        stan::math::validate_non_negative_index("log_B", "M", M);
        std::vector<Eigen::Matrix<double,-1,-1>> log_B =
          std::vector<Eigen::Matrix<double,-1,-1>>(C,
            Eigen::Matrix<double,-1,-1>::Constant(S, M,
              std::numeric_limits<double>::quiet_NaN()));
        current_statement__ = 45;
        stan::math::validate_non_negative_index("log_py", "S", S);
        current_statement__ = 46;
        stan::math::validate_non_negative_index("log_py", "T", T);
        Eigen::Matrix<double,-1,-1> log_py =
          Eigen::Matrix<double,-1,-1>::Constant(S, T,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 48;
        stan::math::validate_non_negative_index("log_A", "T", T);
        current_statement__ = 49;
        stan::math::validate_non_negative_index("log_A", "S", S);
        current_statement__ = 50;
        stan::math::validate_non_negative_index("log_A", "S", S);
        std::vector<Eigen::Matrix<double,-1,-1>> log_A =
          std::vector<Eigen::Matrix<double,-1,-1>>(T,
            Eigen::Matrix<double,-1,-1>::Constant(S, S,
              std::numeric_limits<double>::quiet_NaN()));
        current_statement__ = 52;
        stan::math::validate_non_negative_index("zeros", "S", S);
        Eigen::Matrix<double,-1,1> zeros =
          Eigen::Matrix<double,-1,1>::Constant(S,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 53;
        stan::model::assign(zeros, stan::math::rep_vector(0, S),
          "assigning variable zeros");
        current_statement__ = 73;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 54;
          stan::model::assign(log_Pi,
            stan::math::log_softmax(
              stan::math::add(alpha_i,
                stan::math::multiply(beta_i,
                  stan::model::rvalue(X_i, "X_i", stan::model::index_uni(i))))),
            "assigning variable log_Pi");
          current_statement__ = 70;
          for (int t = 1; t <= T; ++t) {
            current_statement__ = 57;
            for (int s = 1; s <= S; ++s) {
              current_statement__ = 55;
              stan::model::assign(log_A,
                stan::math::transpose(
                  stan::math::log_softmax(
                    stan::math::multiply(
                      stan::model::rvalue(beta_s, "beta_s",
                        stan::model::index_uni(s)),
                      stan::model::rvalue(X_s, "X_s",
                        stan::model::index_uni(t), stan::model::index_uni(i))))),
                "assigning variable log_A", stan::model::index_uni(t),
                stan::model::index_uni(s), stan::model::index_omni());
            }
            current_statement__ = 62;
            for (int c = 1; c <= C; ++c) {
              current_statement__ = 60;
              for (int s = 1; s <= S; ++s) {
                current_statement__ = 58;
                stan::model::assign(log_B,
                  stan::math::transpose(
                    stan::math::log_softmax(
                      stan::math::multiply(
                        stan::model::rvalue(beta_o, "beta_o",
                          stan::model::index_uni(c),
                          stan::model::index_uni(s)),
                        stan::model::rvalue(X_o, "X_o",
                          stan::model::index_uni(t),
                          stan::model::index_uni(i))))),
                  "assigning variable log_B", stan::model::index_uni(c),
                  stan::model::index_uni(s), stan::model::index_omni());
              }
            }
            current_statement__ = 63;
            stan::model::assign(log_py, zeros, "assigning variable log_py",
              stan::model::index_omni(), stan::model::index_uni(t));
            current_statement__ = 68;
            for (int c = 1; c <= C; ++c) {
              current_statement__ = 66;
              if (stan::math::logical_gt(
                    stan::model::rvalue(obs, "obs",
                      stan::model::index_uni(c), stan::model::index_uni(t),
                      stan::model::index_uni(i)), 0)) {
                current_statement__ = 64;
                stan::model::assign(log_py,
                  stan::math::add(
                    stan::model::deep_copy(
                      stan::model::rvalue(log_py, "log_py",
                        stan::model::index_omni(), stan::model::index_uni(t))),
                    stan::model::rvalue(log_B, "log_B",
                      stan::model::index_uni(c), stan::model::index_omni(),
                      stan::model::index_uni(
                        stan::model::rvalue(obs, "obs",
                          stan::model::index_uni(c),
                          stan::model::index_uni(t),
                          stan::model::index_uni(i))))),
                  "assigning variable log_py", stan::model::index_omni(),
                  stan::model::index_uni(t));
              }
            }
          }
          current_statement__ = 71;
          stan::model::assign(ll, loglik(log_Pi, log_A, log_py, pstream__),
            "assigning variable ll", stan::model::index_uni(i));
        }
        current_statement__ = 74;
        log_lik_ = stan::math::sum(ll);
      }
      if (emit_transformed_parameters__) {
        out__.write(log_lik_);
        out__.write(prior_);
        out__.write(alpha_i);
        out__.write(beta_i);
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              out__.write(stan::model::rvalue(beta_s, "beta_s",
                            stan::model::index_uni(sym3__),
                            stan::model::index_uni(sym2__),
                            stan::model::index_uni(sym1__)));
            }
          }
        }
        for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              for (int sym4__ = 1; sym4__ <= C; ++sym4__) {
                out__.write(stan::model::rvalue(beta_o, "beta_o",
                              stan::model::index_uni(sym4__),
                              stan::model::index_uni(sym3__),
                              stan::model::index_uni(sym2__),
                              stan::model::index_uni(sym1__)));
              }
            }
          }
        }
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double prior = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 11;
      prior = prior_;
      double log_lik = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      log_lik = log_lik_;
      out__.write(prior);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(alpha_i_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(alpha_i_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(alpha_i_raw_1dim__),
        "assigning variable alpha_i_raw");
      out__.write_free_positive_ordered(alpha_i_raw);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta_i_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(beta_i_raw_1dim__,
          K_i), "assigning variable beta_i_raw");
      out__.write(beta_i_raw);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        current_statement__ = 3;
        for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
          current_statement__ = 3;
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            current_statement__ = 3;
            stan::model::assign(beta_s_raw, in__.read<local_scalar_t__>(),
              "assigning variable beta_s_raw",
              stan::model::index_uni(sym3__), stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write(beta_s_raw);
      Eigen::Matrix<local_scalar_t__,1,-1> beta_o_raw =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(beta_o_raw_1dim__,
          DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(beta_o_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,1,-1>>(beta_o_raw_1dim__),
        "assigning variable beta_o_raw");
      out__.write(beta_o_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha_i_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(alpha_i_raw_1dim__)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_i_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(beta_i_raw_1dim__),
          static_cast<size_t>(K_i)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta_s_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(S),
          static_cast<size_t>(beta_s_raw_2dim__), static_cast<size_t>(K_s)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "beta_o_raw",
        "double",
        std::vector<size_t>{static_cast<size_t>(beta_o_raw_1dim__)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(alpha_i_raw_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_i_raw_flat__;
        current_statement__ = 1;
        alpha_i_raw_flat__ = context__.vals_r("alpha_i_raw");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= alpha_i_raw_1dim__; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(alpha_i_raw, alpha_i_raw_flat__[(pos__ - 1)],
            "assigning variable alpha_i_raw", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_positive_ordered(alpha_i_raw);
      Eigen::Matrix<local_scalar_t__,-1,-1> beta_i_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_i_raw_1dim__,
          K_i, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_i_raw_flat__;
        current_statement__ = 2;
        beta_i_raw_flat__ = context__.vals_r("beta_i_raw");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
            current_statement__ = 2;
            stan::model::assign(beta_i_raw, beta_i_raw_flat__[(pos__ - 1)],
              "assigning variable beta_i_raw",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta_i_raw);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> beta_s_raw =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(S,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(beta_s_raw_2dim__,
            K_s, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> beta_s_raw_flat__;
        current_statement__ = 3;
        beta_s_raw_flat__ = context__.vals_r("beta_s_raw");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
            current_statement__ = 3;
            for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
              current_statement__ = 3;
              stan::model::assign(beta_s_raw, beta_s_raw_flat__[(pos__ - 1)],
                "assigning variable beta_s_raw",
                stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 3;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write(beta_s_raw);
      Eigen::Matrix<local_scalar_t__,1,-1> beta_o_raw =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(beta_o_raw_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_o_raw_flat__;
        current_statement__ = 4;
        beta_o_raw_flat__ = context__.vals_r("beta_o_raw");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= beta_o_raw_1dim__; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(beta_o_raw, beta_o_raw_flat__[(pos__ - 1)],
            "assigning variable beta_o_raw", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta_o_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha_i_raw", "beta_i_raw",
                "beta_s_raw", "beta_o_raw"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"log_lik_", "prior_", "alpha_i", "beta_i", "beta_s", "beta_o"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"prior", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    alpha_i_raw_1dim__)},
                std::vector<size_t>{static_cast<size_t>(beta_i_raw_1dim__),
                  static_cast<size_t>(K_i)},
                std::vector<size_t>{static_cast<size_t>(S),
                  static_cast<size_t>(beta_s_raw_2dim__),
                  static_cast<size_t>(K_s)},
                std::vector<size_t>{static_cast<size_t>(beta_o_raw_1dim__)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(S)},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(K_i)},
             std::vector<size_t>{static_cast<size_t>(S),
               static_cast<size_t>(S), static_cast<size_t>(K_s)},
             std::vector<size_t>{static_cast<size_t>(C),
               static_cast<size_t>(S), static_cast<size_t>(M),
               static_cast<size_t>(K_o)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= alpha_i_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha_i_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta_i_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
          param_names__.emplace_back(std::string() + "beta_s_raw" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= beta_o_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_o_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik_");
      param_names__.emplace_back(std::string() + "prior_");
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        param_names__.emplace_back(std::string() + "alpha_i" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_i" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta_s" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            for (int sym4__ = 1; sym4__ <= C; ++sym4__) {
              param_names__.emplace_back(std::string() + "beta_o" + '.' +
                std::to_string(sym4__) + '.' + std::to_string(sym3__) + '.' +
                std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }
          }
        }
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "prior");
      param_names__.emplace_back(std::string() + "log_lik");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= alpha_i_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha_i_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_i_raw_1dim__; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta_i_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= beta_s_raw_2dim__; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
          param_names__.emplace_back(std::string() + "beta_s_raw" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= beta_o_raw_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_o_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik_");
      param_names__.emplace_back(std::string() + "prior_");
      for (int sym1__ = 1; sym1__ <= S; ++sym1__) {
        param_names__.emplace_back(std::string() + "alpha_i" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K_i; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta_i" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= K_s; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= S; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta_s" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= K_o; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= S; ++sym3__) {
            for (int sym4__ = 1; sym4__ <= C; ++sym4__) {
              param_names__.emplace_back(std::string() + "beta_o" + '.' +
                std::to_string(sym4__) + '.' + std::to_string(sym3__) + '.' +
                std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }
          }
        }
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "prior");
      param_names__.emplace_back(std::string() + "log_lik");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha_i_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(alpha_i_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"beta_i_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_i_raw_1dim__) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"parameters\"},{\"name\":\"beta_s_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_s_raw_2dim__) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"parameters\"},{\"name\":\"beta_o_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_o_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"log_lik_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"alpha_i\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_i\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_s\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"beta_o\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(C) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(M) + ",\"cols\":" + std::to_string(K_o) + "}}},\"block\":\"transformed_parameters\"},{\"name\":\"prior\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha_i_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(alpha_i_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"beta_i_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_i_raw_1dim__) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"parameters\"},{\"name\":\"beta_s_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(beta_s_raw_2dim__) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"parameters\"},{\"name\":\"beta_o_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_o_raw_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"log_lik_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior_\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"alpha_i\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(S) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_i\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_i) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_s\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(S) + ",\"cols\":" + std::to_string(K_s) + "}},\"block\":\"transformed_parameters\"},{\"name\":\"beta_o\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(C) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(S) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(M) + ",\"cols\":" + std::to_string(K_o) + "}}},\"block\":\"transformed_parameters\"},{\"name\":\"prior\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((alpha_i_raw_1dim__ + (beta_i_raw_1dim__ *
      K_i)) + ((S * beta_s_raw_2dim__) * K_s)) + beta_o_raw_1dim__);
    const size_t num_transformed = emit_transformed_parameters * ((((((1 + 1)
      + S) + (S * K_i)) + ((S * S) * K_s)) + (((C * S) * M) * K_o)));
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((alpha_i_raw_1dim__ + (beta_i_raw_1dim__ *
      K_i)) + ((S * beta_s_raw_2dim__) * K_s)) + beta_o_raw_1dim__);
    const size_t num_transformed = emit_transformed_parameters * ((((((1 + 1)
      + S) + (S * K_i)) + ((S * S) * K_s)) + (((C * S) * M) * K_o)));
    const size_t num_gen_quantities = emit_generated_quantities * ((1 + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_multichannel_nhmm_vvv_namespace::model_multichannel_nhmm_vvv;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_multichannel_nhmm_vvv_namespace::profiles__;
}
#endif
#endif
